### ISSUE TITLE
Passing the digital transformation stink test

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#1]
Ambassador @amatlack proposes a new piece based on her eagerly anticipated and well-received presentation at Red Hat Summit 2019. Suggested talking points: digital transformation, bad tastes and smells, pufferfish, being _literally_ literal, and responding well to change.

**Comment by semioticrobotic** [comment]
Just wondering how this is going, @amatlack, and if there's anything I can do to help you.

**Comment by amatlack** [comment]
Nothing to share yet. Just short on time. :-)

**Comment by semioticrobotic** [comment]
Roger that. Thanks!

**Comment by amatlack** [comment]
I think that this point it's clear this isn't happening, so I'm going to close this out to clean house a bit. Might return with a similar topic one day. :)
