### ISSUE TITLE
Ask the Ambassadors Summer Episodes

### ISSUE THREAD

**Issue by jenkelchner** [open-organization/editorial#103]
Hello Ambassadors!  I'd like to posit a couple of recording dates to do "Ask the Ambassadors".  If we can knock out several questions each time, it will carry us through the summer! 

We can gather questions from Social Media, events we are at, things we have overheard....or we can pull from our past contributions!

If you are interested, email, DM me or drop it below for one of these (or all of them) three opportunities!!

~~Wednesday, June 30th, 8:30AM - 9:30AM~~

Thursday, July 22, 8:15AM - 9:00AM -- just before Ambassador Meeting
Thursday, July 22, 10:00AM - 10:45AM -- just after Ambassador Meeting

**Comment by semioticrobotic** [comment]
Love the idea of connecting this to a community call. I'm in for whatever you might need!

**Comment by LauraHilliger** [comment]
I'm up for this and noted June 30th. I have an invite for the Ambassadors meeting on July 22nd, rather than July 15th – shall I mark the 15th, or pay attention to the "just before" and "just after" and mark the 22nd? 🤔

**Comment by jenkelchner** [comment]
Hey all & @LauraHilliger  specifically, the Ambassador meeting was moved after I set up the 15th. Unfortunately, I'm unavailable on the 22nd so I can keep the 15th for an hour OR do the 29th for an hour.  Please vote on the July times thanks.

**Comment by semioticrobotic** [comment]
This is my fault. I realized I am going to be out of town on July 15 and won't be able to coordinate the monthly meeting if it's scheduled for that date. So I (too hastily) rescheduled it for July 22. But I'd forgotten how that messes with @jenkelchner's excellent plans for recording the next series of episodes. I am happy to revert tot he former meeting date if someone else would like to run it. Or I will simply bow out of participating on this month's panel show (also fine).

**Comment by jenkelchner** [comment]
Hey, everyone!   I have canceled the June 30th session and have set TWO session times up that coordinate with the Ambassador meeting on the 22nd of July.  The recording times will be bookends for the meeting in hopes that some of you will be able to attend and answer a question or two.  

8:00 - 9:00AM EST  and 10:00 - 10:45AM EST on July 22nd.  Happy to send invites! @semioticrobotic @LauraHilliger

**Comment by semioticrobotic** [comment]
Gotcha. Will do. Thanks, @jenkelchner, for your resilience and flexibility here as the meeting date jumped around a bit. Appreciate you. :pray:

**Comment by semioticrobotic** [comment]
Oh, and yes—please add me to an invitation before and/or after (whatever seems to have momentum) and I'll be there.

**Comment by jenkelchner** [comment]
@semioticrobotic I'm adding you and @LauraHilliger  on both times until it shakes out!

**Comment by funnelfiasco** [comment]
@jenkelchner please add me to both times, too!

**Comment by jenkelchner** [comment]
Recording of 6. new episodes completed today!! Thank you to those who participated!  I'll be closing this and opening episode cards now for production and scheduling.
