### ISSUE TITLE
Handling public comment on proposals

### ISSUE THREAD

**Issue by funnelfiasco** [open-organization/editorial#104]
From a conversation with Ron, Heidi, and Bryan happening right now about how we handle comments on the new Open Leadership Definition.

* How to know what comments to reply to
* Interact with comments in the doc
* Provide a summary at the end (so keep notes in a spreadsheet or a text doc)

**Comment by semioticrobotic** [comment]
Great idea, @funnelfiasco. Thanks for jotting this down.

**Comment by LauraHilliger** [comment]
Happy to help, I just looked at some of the comments in Preamble and got all excited about working through them. I <3 community feedback!!

My $.02
> How to know what comments to reply to
I think each person gets ONE Reply (unless they're trolly, of course), we could invite them to our regular calls, if they're keen to participate? "Hi so-and-so, Thanks for commenting in our docs! We're going to work through your comments in our open, biweekly call. It's Tuesdays, starting the week after next (or whatevs)... You can join anytime, here's a link..." 

> Interact with comments in the doc
See above, then we resolve comments when we've discussed, taking notes in some open doc (probably the spreadsheet, +1 to Ben's comment about taking notes.)

> Provide a summary at the end (so keep notes in a spreadsheet or a text doc)
After looking at some of the comments I think there are some that I'd integrate immediately, some that I'd like to discuss with you lot, and some that I would have a rationalization for ignoring. If we use the call to work through them, we can catalogue as one of the three groups and after a bit write a blogpost.

**Comment by semioticrobotic** [comment]
Thanks for your great reply, @LauraHilliger. @funnelfiasco can correct me if I'm wrong, but I *think* he meant for this ticket to signal a more general article outlining a process for reviewing and vetting feedback that *any* open leader could use for *any* project in an open organization—not necessarily a specific discussion of our plans for the Open Leadership Definition (collected in #94). But @funnelfiasco can surely correct me if I'm wrong.

**Comment by funnelfiasco** [comment]
I don't think there's anything I'd add to what Laura wrote in her recent article, so I'll take this one off the pile.
