### ISSUE TITLE
Japan at a crossroads: How open organization principles aided the country's economic resurgence

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#106]
This will be the second part of @RonMcFarland's review of *The Business Reinvention of Japan,* which began in June. It's a two-part series. @semioticrobotic is working with @RonMcFarland on publication.

**Comment by semioticrobotic** [comment]
Draft finished and @semioticrobotic now reviewing.

**Comment by semioticrobotic** [comment]
Also tapping @trncb for a little extra editorial polish on this part, too (Part Two, too?). But he should feel free to decline if we're overloading him.

@trncb: We'd like to begin publishing this series during the first week of July, if possible.

**Comment by semioticrobotic** [comment]
Scheduled for publication on July 15, 2021.

**Comment by semioticrobotic** [comment]
Forgot to note that this was [published](https://opensource.com/open-organization/21/7/japan-innovation-crossroads)! Nice work on another great series, @RonMcFarland.

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn

**Comment by RonMcFarland** [comment]
Yes, I'm getting good fee on it.  Even the book author responded.
