### ISSUE TITLE
Guide for Educators roundtable

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#108]
Ambassador @engineerteacher is organizing a roundtable discussion on open educational organizations and *The Open Organization Guide for Educators*, featuring the book's editors. @engineerteacher, @semioticrobotic, and @afchernik. Initial plan is to record for OpenOrgTV.

**Comment by jenkelchner** [comment]
Excellent!!!  This was on my wish list so happy to moderate and/or just do the edits! @semioticrobotic @engineerteacher

**Comment by semioticrobotic** [comment]
Great! Thanks, @jenkelchner. When @engineerteacher gathers the participants for a planning call this week, we'll be able to report back with what we're thinking and what we may need.

**Comment by engineerteacher** [comment]
Thanks, @jenkelchner! Today's call is to plan next steps, but do feel free to join us: https://us02web.zoom.us/j/9722256204. I love the idea of you moderating an informal conversation.

**Comment by semioticrobotic** [comment]
@jenkelchner: Would you be available to moderate this episode/discussion some time during the week of August 23, 2021? We're thinking the beginning of the week is best.

If so, we'll provide a briefing document that should ease the work for you.

**Comment by jenkelchner** [comment]
@semioticrobotic I'll be on PTO starting that day for 3 weeks.   I haven't locked that day in for travel yet, **so I would be agreeable to moderate the day of 23rd**...

**Comment by semioticrobotic** [comment]
Great! Thanks so much, @jenkelchner. @engineerteacher and @afchernik, does this (:point_up:) align with your schedules? I would personally prefer the 24th but could make either work, really.

**Comment by afchernik** [comment]
Yes! On 8/23 I could do after 1:00. On 8/24 I could do before 11:00 or
after 2:00.

**Comment by jenkelchner** [comment]
This _"On 8/24 I could do before 11:00"_ would work for me!

**Comment by semioticrobotic** [comment]
Alright then! Seems like we're all converging on **August 24, 2021 I could do before 10:00**. Let's go ahead and lock that in. @jenkelchner, would you do the honors of sending the invitation and the video link you'd like us to use? This way we can be sure you'll get what you know is easiest to work with.

In the meantime, @engineerteacher, @afchernik, and I will put our heads together to develop that briefing document for you.

**Comment by afchernik** [comment]
Wonderful! Looking forward to working with you all on this!

**Comment by jenkelchner** [comment]
> Alright then! Seems like we're all converging on **August 24, 2021 at 10:00**. Let's go ahead and lock that in. @jenkelchner, would you do the honors of sending the invitation and the video link you'd like us to use? 

you got it!

**Comment by jenkelchner** [comment]
Currently in-production and scheduling for a release on September 8th @semioticrobotic

**Comment by semioticrobotic** [comment]
Noted and logged! Thank you, @jenkelchner.

**Comment by jenkelchner** [comment]
@afchernik @semioticrobotic @engineerteacher  - I'm done with all editing. Comes to a full version at 44 mins but honestly, I suggest we keep it at this longer length because of the conversation flow. I attempted to break it up and it just doesn't work. 

If you have any notes, links, etc to add to the YouTube page for this roundtable, just send them over by Tuesday end of day and I'll add it to the page before it publishes Wednesday!! :) :)  

I'll update this later with a URL for social sharing as well.

**Comment by semioticrobotic** [comment]
Thanks, @jenkelchner! Will we have a chance to review before it goes live?

**Comment by jenkelchner** [comment]
Yep, when it's done processing I can set it as unlisted and then won't set the publish time until end of day tomorrow ... that way you can view!

**Comment by semioticrobotic** [comment]
Thank you!

**Comment by engineerteacher** [comment]
Thanks, Jen! Looking forward to watching it.

Cheers!

-Ben

Ben Owens

*Co-Founder & Lead Innovation Engineer*
*Open Way Learning* <http://openwaylearning.org/>
706.878.8946
*Co-Author of Open Up, Education!
<https://www.amazon.com/Open-Up-Education-Learning-Transform/dp/1475842007/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr=>
*
* | **National Faculty - PBLWorks
<https://www.pblworks.org/author/ben-owens> | Open Organization Ambassador
<https://opensource.com/users/engineerteacher>*
*Connect: @engineerteacher <https://twitter.com/engineerteacher>, Linkedin
<https://www.linkedin.com/in/ben-owens-0a8a9875/> or Calendly
<https://calendly.com/ben-openwaylearning>*

**Comment by semioticrobotic** [comment]
Love watching this, @jenkelchner. Note from me as I go through it: When I hit the 17:00 mark, my video freezes and sound stops, though the playback counter keeps going. Then at 17:23 it "unsticks." Not sure if you're also seeing this or if it's just my copy, but wanted to report. If it's not just me, know that you won't hurt my feelings if you need to chop out the weird silence and the end of my answer to the question (I'm starting to ramble by that point anyway).

**Comment by jenkelchner** [comment]
Ugh. I hate that...after all the hours in editing that came through via the upload. grrrr.  Okay, given time factors all around, I will cut that space that froze. It will go back into a reprocessing phase for a couple hours in YouTube...sorry.  Still need to get any links and info from @engineerteacher that he'd like in the copy :)

**Comment by afchernik** [comment]
Can someone please share the video link with me? I looked on GitHub but
despite what you all say it is *not* user friendly :-)

**Comment by jenkelchner** [comment]
I hadn't posted it here lol but will email you directly!!

**Comment by afchernik** [comment]
Thank you!!

**Comment by semioticrobotic** [comment]
Thanks, @jenkelchner. You're a :star:. I'm sorry this happened to the video. But honestly, I think if we just cut my answer at 16:41 and let the next person speak, everyone wins. :laughing:

**Comment by jenkelchner** [comment]
We are good to go for tomorrow folks: https://www.youtube.com/watch?v=t6GQFxE3uGk

**Comment by engineerteacher** [comment]
🙌🙂
Ben Owens

*Co-Founder & Lead Innovation Engineer*
*Open Way Learning* <http://openwaylearning.org/>
706.878.8946
*Co-Author of Open Up, Education!
<https://www.amazon.com/Open-Up-Education-Learning-Transform/dp/1475842007/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr=>
*
* | **National Faculty - PBLWorks
<https://www.pblworks.org/author/ben-owens> | Open Organization Ambassador
<https://opensource.com/users/engineerteacher>*
*Connect: @engineerteacher <https://twitter.com/engineerteacher>, Linkedin
<https://www.linkedin.com/in/ben-owens-0a8a9875/> or Calendly
<https://calendly.com/ben-openwaylearning>*

**Comment by semioticrobotic** [comment]
Congratulations, all. And thanks @jenkelchner for the usual amazing video editing.

**Comment by jenkelchner** [comment]
Promoting: 

- [ ] Twitter
- [ ] LinkedIn
- [ ] Discourse
