### ISSUE TITLE
An update on the Open Leadership Definition

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#109]
New article from @LauraHilliger updating readers on revisions to the Open Leadership Definition (#94) and outlining our collaborative process for moving forward.

**Comment by semioticrobotic** [comment]
Today I added my own thoughts and revisions to what @LauraHilliger had! Think [it's looking great](https://docs.google.com/document/d/1zgWLY2SU-mI6iOWeO4JUASY9FxEFeCLkyGzJ96kHwxA/edit?usp=sharing).

**Comment by semioticrobotic** [comment]
@LauraHilliger made some changes and I made some changes to those changes. I think maybe we're ready to go to production? Will let @LauraHilliger make that call.

**Comment by LauraHilliger** [comment]
Looks good to me, we can ship this week :D

**Comment by semioticrobotic** [comment]
Will work to typeset ASAP! Thanks.

**Comment by semioticrobotic** [comment]
Scheduled for publication on July 22, 2021. Nice work, @LauraHilliger!

**Comment by semioticrobotic** [comment]
[Published](https://opensource.com/open-organization/21/7/manage-feedback-open-project)! Thanks so much for doing this, @LauraHilliger!

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn
