### ISSUE TITLE
ATA EP08 | How can I encourage open conversations?

### ISSUE THREAD

**Issue by jenkelchner** [open-organization/editorial#115]
Ambassadors respond to the following question:

> Open organizations thrive on honest dialog, how can I encourage (and participate in) open conversations without hurting anyone's feelings or making people uncomfortable?

**Comment by jenkelchner** [comment]
Publishes September 1st 
https://www.youtube.com/watch?v=_NhlWzV2_BQ

**Comment by LauraHilliger** [comment]
### Promotion checklist

- [] Discourse
- [] Twitter
- [x] LinkedIn
