### ISSUE TITLE
ATA EP09 - building trust

### ISSUE THREAD

**Issue by jenkelchner** [open-organization/editorial#116]
Ambassadors respond to the following question:

> It seems like building open organizations requires trust. What are some ways I can begin building that trust among managers, leaders, and team members?

**Comment by jenkelchner** [comment]
Scheduled for publication on September 15 - https://www.youtube.com/watch?v=DZ3Ky7SfIgc

**Comment by jenkelchner** [comment]
Ready for promotion:

- [ ] Twitter
- [ ] LinkedIn
- [ ] Discourse

**Comment by semioticrobotic** [comment]
Another great episode! Well done, @jenkelchner!
