### ISSUE TITLE
A guide to understanding your team's implicit values and needs

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#117]
The first part of Ron's next serialized book review.

**Comment by semioticrobotic** [comment]
First part of book review now finalize and ready for production. I'll get this typeset some time next week.

**Comment by RonMcFarland** [comment]
Sounds good.

**Comment by semioticrobotic** [comment]
Scheduled for publication on August 19, 2021.

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn
