### ISSUE TITLE
Know your organization's rule makers and rule breakers

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#118]
This will be the second part of Ron's review of _Rule Makers, Rule Breakers)_.

**Comment by semioticrobotic** [comment]
Looks like we've wrapped up edits here. Great! @RonMcFarland, would you prefer to hold this one from publication until you've recorded the video that will accompany it? Or should we publish and add the video later? Whatever your preference, it's fine with me. Just checking.

**Comment by RonMcFarland** [comment]
I guess waiting for the recording to be completed would be best so the
readers don't have to wait around for it.

**Comment by semioticrobotic** [comment]
Okay! I have typeset the article and [it is ready for review](https://opensource.com/open-organization/21/8/rule-makers-rule-breakers). Seeking @jenkelchner feedback and final approval of [the video component](https://youtu.be/S_z120e65Ks), uploaded and edited, but private.

**Comment by jenkelchner** [comment]
@semioticrobotic - can I get a preferred publication date please?

**Comment by semioticrobotic** [comment]
Absolutely! We are aiming for August 26, but need to coordinate with the Opensource.com team.

**Comment by jenkelchner** [comment]
If that works for them, I can push ATA EP08 back a week and publish Ron's review on 8/25?   If it needs to roll WITH article, we can do same day release.

**Comment by semioticrobotic** [comment]
As long as you are okay with delaying ATA EP08 for a week, then I like the idea of launching the video a day early. That way, when the article goes live, we don't have to worry about whether the video was timed to go live with it (it'll already be up!).

Is that okay with you? I will put the August 26 request in right now.

**Comment by jenkelchner** [comment]
@semioticrobotic DONE!!  :)  I could use a few extra days to get the next round of content ready anyway so this works PERFECTLY on my end.  All set for release 8/25!

**Comment by semioticrobotic** [comment]
I love it when a good plan comes together. You're the best. Thank you! :pray:

**Comment by semioticrobotic** [comment]
All components approved and scheduled for publication on August 26, 2021.
