### ISSUE TITLE
When leading openly means leading with vulnerability

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#123]
This is the next installment of @HeidiHVL's "Managing with Open Values" series, and her third and final interview with @samuelknuth.

**Comment by HeidiHVL** [comment]
Thanks @semioticrobotic !

**Comment by trncb** [comment]
@semioticrobotic @HeidiHVL I've had a read through and made some suggestions. 

What a great article @HeidiHVL!

**Comment by semioticrobotic** [comment]
You're awesome, @trncb. Thanks so much.

**Comment by semioticrobotic** [comment]
Reviewed the suggestions from @trncb and appreciate them very much. Will let @HeidiHVL review and determine how she'd like to take them on. We have some time here, as @samuelknuth is currently reviewing Part II.

**Comment by semioticrobotic** [comment]
I've re-read the piece and think it's good to go, @HeidiHVL! Let's get @samuelknuth comments, and then we can put this into production.

**Comment by HeidiHVL** [comment]
Thanks @semioticrobotic - I really like this article because of it's connection to my research on innovation and creativity. Looking forward to @samuelknuth feedback :)

**Comment by semioticrobotic** [comment]
It's really good, @HeidiHVL! I can't wait for it to get published.
