### ISSUE TITLE
Four new videos about working and leading openly

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#126]
This article summarizes and links to the great videos we released on OpenOrgTV in September. @jenkelchner and @semioticrobotic [working on it](https://notes.theopenorganization.org/NsQbp1phQWOZGgQp7FGNiQ?view).

**Comment by jenkelchner** [comment]
@semioticrobotic - I've updated the final paragraph for your review.... please ensure i have my links right thanks!!!!! :)

**Comment by semioticrobotic** [comment]
Awesome! Thank you, @jenkelchner! I'm adding an intro paragraph now. Any other general feedback or instructions? Otherwise, I can work on getting this into production for publication in the first week of October.

**Comment by semioticrobotic** [comment]
Oh yes, and @jenkelchner: Not sure if this is in the cards for you right now (and okay if not), but would you have a moment to make an Opensource.com article header image that features the OpenOrgTV logo? Dimensions are 520px X 292px.

Not a blocker for release, obviously, so don't worry if not possible in a week or so!

**Comment by jenkelchner** [comment]
I think I've contributed all I can on this month!  I'd love to also make a video mashup each month like a teaser trailer...but that will have to wait for now!  Maybe I'll start that for the year end - first 6 months wrap up :)

**Comment by jenkelchner** [comment]
> Oh yes, and @jenkelchner: Not sure if this is in the cards for you right now (and okay if not), but would you have a moment to make an Opensource.com article header image that features the OpenOrgTV logo? Dimensions are 520px X 292px.
> 
> Not a blocker for release, obviously, so don't worry if not possible in a week or so!

I'll see if I can't get that out tomorrow! shouldn't take long

**Comment by semioticrobotic** [comment]
Okay! Thanks.

**Comment by semioticrobotic** [comment]
Off to @jenkelchner and the Opensource.com team for final review, approvals, and scheduling.

**Comment by semioticrobotic** [comment]
[Published](https://opensource.com/open-organization/21/10/sept-openorgtv-roundup)! Thanks, @jenkelchner!

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn
