### ISSUE TITLE
Author conversation about Opening Up to Leadership Talent

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#127]
@RonMcFarland and @JosGroenNL to chat about @JosGroenNL recently released volume in the *Open Perspectives* series, "[Opening Up to Leadership Talent](https://raw.githubusercontent.com/open-organization/open-perspectives/main/opening-up-to-leadership-talent/opening-up-to-leadership-talent.pdf)."

I'm thinking this might be the start of a new playlist, "Open Perspectives," that features in-depth interviews with the authors behind series installments. But I defer to @jenkelchner on that.

**Comment by semioticrobotic** [comment]
This is recorded and I am reviewing raw footage presently! Will connect with @jenkelchner when we're in production.

**Comment by semioticrobotic** [comment]
The video is now processing and I'll update everyone when it's finished.

**Comment by semioticrobotic** [comment]
Okay! The video is processed and trimmed. Passing to @jenkelchner for her final review, flourishes, and scheduling.

**Comment by jenkelchner** [comment]
@semioticrobotic I'll be able to work on this tomorrow!

**Comment by semioticrobotic** [comment]
Awesome! Thanks, @jenkelchner!

**Comment by jenkelchner** [comment]
Okay, the video is complete now.  New playlist created "Open Perspectives" - btw, we can tag both Rons Reviews and Open Perspectives if you'd like. Just let me know!

Scheduling for our next pub date which is Wednesday, December 8th: https://www.youtube.com/watch?v=fyJBeFVBYyA

@semioticrobotic

**Comment by JosGroenNL** [comment]
👍👌

Met vriendelijke groet,

Jos Groen

**Comment by semioticrobotic** [comment]
Thanks, @jenkelchner! You're the best.

I like the "dual listing" approach for this one—since it's technically an episode of Ron's show but also the first video we've done in this important series of new publications. I think I can manage to make that update in YouTube without messing things up. :laughing:

**Comment by jenkelchner** [comment]
- [ ] LinkedIn
- [ ] Discourse
- [ ] Twitter
