### ISSUE TITLE
 Open exchange, open doors, open minds: A recipe for global progress 

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#129]
Proposed new writing/review collaboration from @RonMcFarland, Brook Manville, and @semioticrobotic: a review and accompanying critique of Johan Norberg's _Open: The Story of Human Progress_.

**Comment by semioticrobotic** [comment]
@RonMcFarland has drafted this article and it's now with me for editing.

**Comment by semioticrobotic** [comment]
Brook Manville has also penned a multi-part review and I'm working on editing that, too.

**Comment by semioticrobotic** [comment]
I'm typesetting this now and getting it into production for @RonMcFarland.

**Comment by semioticrobotic** [comment]
Confirmed scheduled for publication on March 15!

**Comment by semioticrobotic** [comment]
Neglected to note that [this was published](https://opensource.com/open-organization/22/3/open-history-human-progress)! Nice work, @RonMcFarland!

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn

**Comment by RonMcFarland** [comment]
Bryan,

I saw it.  Thanks for your work on it.  Looking forward to the next one.

Ron
