### ISSUE TITLE
 Looking into the future of collaborative commons

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#140]
Third and final installment of this review series from @RonMcFarland.

**Comment by semioticrobotic** [comment]
@RonMcFarland, do you happen to have a title and/or publication date for this article yet?

**Comment by RonMcFarland** [comment]
I think they are still working on it.  I haven't heard.

Ron

**Comment by semioticrobotic** [comment]
[Published May 27, 2022](https://opensource.com/open-organization/22/5/looking-future-collaborative-commons).

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn
