### ISSUE TITLE
 Applying smart thinking to open organization principles

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#142]
Forthcoming article from @RonMcFarland.

**Comment by semioticrobotic** [comment]
@RonMcFarland: Please just let us know when you receive publication dates/schedules from Opensource.com. Thanks!

**Comment by AmyJuneH** [comment]
This has a tentative publish date of June 23 - this will be the live link: https://opensource.com/article/22/6/applying-smart-thinking-open-organization-principles

Here is the preview link for Ron's review:  https://opensource.com/preview-link/node/70075/36270486-5905-49c4-b4a2-6aed21d56350

**Comment by AmyJuneH** [comment]
This was published today
https://opensource.com/open-organization/22/6/applying-smart-thinking-open-organization-principles

**Comment by RonMcFarland** [comment]
The other article is in copy editing, but sure! Send along a draft.

Have a great weekend,
*~ AmyJune Hineline, CPACC*
Senior Community Manager - Opensource.com
pronouns: she / her
twitter: volkswagenchick <https://twitter.com/volkswagenchick>
linkedIn: AmyJune Hineline <https://www.linkedin.com/in/volkswagenchick/>
drupal.org: volkswagenchick <https://www.drupal.org/u/volkswagenchick>


I am emailing today from Northern California. I acknowledge my presence on
the traditional homelands of the Ohlone people and pay gratitude and
respect to the Indigenous people – past, present, and future – who have
stewarded this land. If you do not know the land on which you reside, I
encourage you to learn more at https://native-land.ca/.

**Comment by semioticrobotic** [comment]
Thanks, all!

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn

**Comment by semioticrobotic** [comment]
Closing and archiving.
