### ISSUE TITLE
An open conversation about open societies

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#143]
[As discussed at](https://www.theopenorganization.community/t/june-09-2022-meeting/349) this month's meeting of the Open Organization Ambassadors: We'd like @RonMcFarland to write a brief (one- or two-paragraph) recap of our conversation with author Johan Norberg so that we can cross-post the video recording of our roundtable conversation between OpenOrgTV and Opensource.com.

@RonMcFarland, I (@semioticrobotic) can work with you on this if you'd like to collaborate.

**Comment by semioticrobotic** [comment]
The video has been published so we're now able to work on this, @RonMcFarland!

Our goal here is to write a brief introduction/teaser to the video—something that describes what it is and why someone would want to watch it. This should be no longer than, say a paragraph or two.

Then we'll publish that introduction as an article on Opensource.com, embed the video interview in the article, and link to the entire series for readers.

Is this something you're able to work on, @RonMcFarland? I am happy to help as needed.

I've created a workspace here:

https://notes.theopenorganization.org/c8L51c9ETOyGO3gQfZnSvA#

Relevant links are here:

- https://www.youtube.com/watch?v=93lwexPTcAM
- https://opensource.com/open-organization/22/3/open-history-human-progress
- https://opensource.com/open-organization/22/3/making-case-openness-engine-human-progress
- https://opensource.com/open-organization/22/4/essence-of-openness-norberg-review
- https://opensource.com/open-organization/22/4/open-world-inclusivity-norberg-review

**Comment by RonMcFarland** [comment]
Bryan,

I'll work on an introduction in a paragraph or two for your review.  Give
me a day or two.

Ron

**Comment by RonMcFarland** [comment]
Bryan,

What about something like this?
******
Why do some societies advance while others weaken?  According to Professor
Norberg’s research, being “open” is a major factor.  I believe his
conclusions are true for organizations as well. This is why his material is
so important and why Brook Manville and I wrote two articles each on his
material. Happily, we were able to have a discussion with Professor Norberg
on exactly what is being “open” in the hopes of finding guidelines and
approaches that will move us toward the greater good for the entire global
community.  Here is the discussion:
********
Please feel free to improve on this any way you like.

Thanks,

Ron

**Comment by semioticrobotic** [comment]
Thanks so much for getting us started here, @RonMcFarland! I will take a look (and work on this [in the document](https://notes.theopenorganization.org/c8L51c9ETOyGO3gQfZnSvA#).

**Comment by semioticrobotic** [comment]
Draft sent to @AmyJuneH and the Opensource.com team! Thanks, @RonMcFarland!

**Comment by AmyJuneH** [comment]
From the OSDC side of things, this has moved into copy editing with a due date of June 23. I will send a preview link for review when it becomes available.
Thanks!

**Comment by AmyJuneH** [comment]
update:
the due date in copy editing was pushed until June 28.

**Comment by AmyJuneH** [comment]
Here is the preview link for review:
Link: https://opensource.com/preview-link/node/70092/ad18c47a-296c-4b95-8850-1da45639958d

Let me know if you have any edits

**Comment by RonMcFarland** [comment]
Just review the discussion again.  It looks great to me as is.  Thanks All

**Comment by semioticrobotic** [comment]
Thanks, @AmyJuneH! Just one note from me:

> And how might we locate guidelines and approaches that will move everyone toward a greater good for the entire global community.

This sentence should be punctuated with a question mark, not a period.

Otherwise, all looking great from my end! Thanks!

**Comment by AmyJuneH** [comment]
Fixed!

https://opensource.com/article/22/6/our-interview-johan-norberg will be the live link, looks like publication is set for July 11

**Comment by RonMcFarland** [comment]
Great.  I'll let people know.

**Comment by semioticrobotic** [comment]
Excellent! Thanks, @AmyJuneH!

**Comment by semioticrobotic** [comment]
Published today and looking great! Thanks, @AmyJuneH!

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn
