### ISSUE TITLE
Open organizations and industrial disruption (Part 1)

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#144]
First article in a new series on this subject from @RonMcFarland.

**Comment by semioticrobotic** [comment]
@RonMcFarland, can you please add details here when you have a moment? Thanks.

**Comment by RonMcFarland** [comment]
This is a 2-part article on the Open Organization Principle of Adaption in industrial disruption through new technology and cost reduction.  I completed the first draft, and it is gone through one edit review by Seth.

**Comment by semioticrobotic** [comment]
Great! Thanks for the details, @RonMcFarland.

**Comment by RonMcFarland** [comment]
I also put the next article into the schedule.  Still trying to get used to doing this.

**Comment by semioticrobotic** [comment]
Excellent work, @RonMcFarland. You're doing great and I really appreciate it.

**Comment by RonMcFarland** [comment]
Yes, there are two parts on this subject.

**Comment by AmyJuneH** [comment]
Part one is ready for review. Here is the preview link:  https://opensource.com/preview-link/node/70139/a26c61a5-d6e2-47b5-bc6f-f5d7ff44c6c9

I also will email this to Ron, thanks.

**Comment by RonMcFarland** [comment]
Here are some comments......
1.  In the first page, "Could a such community be formed?".  In think, "such a ...." is better.

2.  In  "3. Use of solar power generation over nuclear power generation", I think, "Here are some consideration for solar power generation:" should be "considerations".

3.  In this sentence, "Solar now regularly provides 20-35% of Germany's power through solar power.", "through solar power" can be deleted.

Other than these small changes, the article looks great to me.

**Comment by AmyJuneH** [comment]
CHanges made, thanks.

Live URL will be:
https://opensource.com/open-organization/22/8/energy-disruption

Set to publish ~August 8

**Comment by semioticrobotic** [comment]
Thanks, all! I'm not sure "Open Organizations" needs to be capitalized in the headline. We don't typically invoke it as a proper noun unless we're talking about the project or the community ("the Open Organization project," etc.). The same is true in instances like "Assume we want to build an Open Organization Community to introduce three things:"—here Ron isn't speaking of _the_ Open Organization community, but rather the common-noun concept of _an_ open organization community.

A minor nit to pick, perhaps. But it's the only thing I can offer when everything else looks good!

Thanks!

**Comment by AmyJuneH** [comment]
This has been published:
How open organizations can harness energy disruptions
https://opensource.com/open-organization/22/8/energy-disruption?sc_cid=7016000000127ECAAY

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn

**Comment by semioticrobotic** [comment]
Thanks for your great work, @AmyJuneH and @RonMcFarland!

**Comment by AmyJuneH** [comment]
I dont see the part 2 card. I'll put both URLS here

Saving home energy using open organization principles (part one)
https://opensource.com/open-organization/22/9/saving-home-energy-open-organization-principles
set to publish ~Sept 5

Applying open organization principles to save factory energy (part 2)
https://opensource.com/open-organization/22/9/saving-factory-energy-open-organization-principles
Set to publish ~Sept 6

**Comment by semioticrobotic** [comment]
Thanks, @AmyJuneH! They're both sitting in `Awaiting Final Approvals`. But now that we're all set, I'll attached the links and get them moving along. Appreciate it!
