### ISSUE TITLE
Comparing solar power to traditional power generation the open way

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#145]
Next article on open organizations and industrial disruption from @RonMcFarland.

**Comment by semioticrobotic** [comment]
Thanks, @AmyJuneH. I think you're correct (though @RonMcFarland will know for sure). I went ahead and edited the issue title to reflect the headline.

You're right that we should iron out this part of the workflow. The Opensource.com team makes final determinations on headlines, and we don't know those headlines until we review typeset drafts of articles. I am always happy to update our editorial issues accordingly, but can only do so after we have access to a draft piece (at which point the headline is typically set!). I hope this makes sense (still a little early here—ha!).

**Comment by AmyJuneH** [comment]
Published today and promoted through Opensource.com

Comparing solar power to traditional power generation the open way by @RonmcfarlMc
Considering all of the benefits, it seems anyone can generate excitement around open organization community projects regarding either solar or wind power.

https://opensource.com/open-organization/22/8/solar-power-vs-traditional-power

**Comment by semioticrobotic** [comment]
Great! Thanks, @AmyJuneH!

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn
