### ISSUE TITLE
Team of Teams review, part 2

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#151]
Second part of Ron's review of *Team of Teams*, concerning organizational charts.

**Comment by AmyJuneH** [comment]
"How innovative Open Organization charts work in practice" is ready for review. Here is the preview link:
Link: https://opensource.com/preview-link/node/70251/120a856b-0102-4ed3-8915-a50556a914a3

**Comment by AmyJuneH** [comment]
We made Ron's suggested edits and swapped out an incorrect image.

Tentatively - the live URL will be: https://opensource.com/article/22/10/innovative-open-organization-chart-works
Set to publish Oct 25

**Comment by RonMcFarland** [comment]
All is great to go to me.  These two articles will go nicely with our Leadership Assessment hard launch activities.
