### ISSUE TITLE
Community leadership, the "introducer-in-chief" (Part 2)

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#153]
Part 2 of series from Ron McFarland.

**Comment by AmyJuneH** [comment]
This is ready for review, here is the preview link
Community thinking patterns and the role of the introducer-in-chief 
Link: https://opensource.com/preview-link/node/70409/53d5f166-825c-4ba1-9e12-b051a6b2401d

**Comment by RonMcFarland** [comment]
Hi AmyJune,

In general, this article looks great.

Notice the sentence, "According to the researchers, you can identify people
who want to improve their situation and are willing to work on it. You
convince these people that they have the choice to improve themselves and
their situation."  It might be better if it went something like this.
"According
to the researchers, you *have to* identify people who want to improve their
situation and are willing to work on it. *Then, *you convince these people
that they have the choice to improve themselves and their situation."

I think this small change might be better.  Otherwise, it's great and ready
to go.

Thanks,

Ron

**Comment by RonMcFarland** [comment]
Note, this is part 1 only.  I don't see a reviewed and edited version of part 2 yet.

**Comment by RonMcFarland** [comment]
Note this Part #1 only.  I don't see Part #2.

Ron

**Comment by AmyJuneH** [comment]
Apologies, this is part one. I'll reference these comments in card #149

**Comment by AmyJuneH** [comment]
Part two was published and socail media is scheduled for around 1pm tomorrow
https://opensource.com/article/23/2/community-thinking-pattern

**Comment by RonMcFarland** [comment]
AmyJune,

I just read the article, even put it a comment and I think it is great.

Notice at the bottom:  This paragraph appears twice and one should be
deleted.

****************************************************

*"What community are you in?*

In your working environment, think about its greater purpose, and consider
listening quality, problem-solving quality, ongoing job support, and
participation level. Rank those factors from one to four and consider where
development is needed. On average, a 3.5 would indicate a competitive
thinking pattern #3 community and 4.5 an internally collaborative thinking
pattern #4 community. To confirm the group thinking pattern level, also ask
yourself what general feeling sticks out among most members:

   - Life is miserable
   - My life is miserable
   - I'm great
   - We're great
   - Life's great

Armed with that information, consider what action is required."

****************************************
Could you delete the above one?

Also, in the sentence, "Bob studies a spare computer there in the company
during his spare time."  Could you add the word "*on*"?  Bob studies *on* a
spare computer there in the company during his spare time.

Furthermore, in the sentence, "Consider *listing* *quality*, *problem-solving
quality*, *ongoing job support*, and *participation level*.", could you
change "*listing*" to "*membership listening*"?

Overall, I really like this article and think the much improved "Community
thinking patterns in action" really brings the content alive.

Cheers,

Ron

**Comment by AmyJuneH** [comment]
Great! Changes made

**Comment by RonMcFarland** [comment]
Thanks!

**Comment by RonMcFarland** [comment]
AmyJune,

I just had a quick look at the article.  A couple comments....

1.  Regarding, this deletion.....

******************
*What community are you in?*

In your working environment, think about its greater purpose, and consider
membership listening quality, problem-solving quality, ongoing job support,
and participation level. Rank those factors from one to four and consider
where development is needed. On average, a 3.5 would indicate a competitive
thinking pattern #3 community and 4.5 an internally collaborative thinking
pattern #4 community. To confirm the group thinking pattern level, also ask
yourself what general feeling sticks out among most members:

   - Life is miserable
   - My life is miserable
   - I'm great
   - We're great
   - Life's great

Armed with that information, consider what action is required.

************

it seems the below one was deleted and the above one remained.  That is the
conclusion of the article, so could you move it to the end?

2.  Have a look at where "*on*" was placed in this sentence. "Bob studies a
spare *on *computer there in the company during his spare time."  Could you
move it to here?  "Bob studies *on* a spare computer there in the company
during his spare time."

Other than that, looks great to me.

Ron

**Comment by semioticrobotic** [comment]
Thanks, @AmyJuneH and @RonMcFarland! I'll begin promoting next week.
