### ISSUE TITLE
Open organization principles and the sharing economy

### ISSUE THREAD

**Issue by RonMcFarland** [open-organization/editorial#154]
The sharing economy is using Open Org Principles.  In this 3-part article series, I will 1-explain characteristics of the sharing economy, 2-Give examples of sharing businesses today and 3-Project the future of sharing.

App development is very important in this business model.  Therefore, I think many will find it interesting and generate app development ideas.

**Comment by RonMcFarland** [comment]
I received a draft of the first part of this article.  It really has been improved.  I gave a handful of minor change suggestions.  Other than that, it looks ready to be posted.

**Comment by AmyJuneH** [comment]
I forgot to post a comment here, yes, i sent a preview link and made most of Ron's suggestions. There were some link requests and I pinged Lauren about inserting those

The sharing economy and the open organization 
Link: https://opensource.com/preview-link/node/70570/a2c3b7ae-04c5-4fe7-aa8c-704c5d83bde5

The tentative publish date is  ~April 19.

**Comment by AmyJuneH** [comment]
Great, I got the requested edits in for the second article and it looks like it's slated to be published ~April 20.

**Comment by AmyJuneH** [comment]
The last one is up for review

The future of the sharing business model
Link: https://opensource.com/preview-link/node/70577/6fde4212-8820-4763-9c92-c3b660be5b54

**Comment by AmyJuneH** [comment]
Article one will go live 3am ET on April 18.
The URL:
https://opensource.com/article/23/4/sharing-economy-open-organization

**Comment by semioticrobotic** [comment]
Looks like this series is completely published as of today!

- [The sharing economy and the open organization](https://opensource.com/article/23/4/sharing-economy-open-organization)
- [Real-world examples of the sharing economy](https://opensource.com/article/23/4/sharing-economy-examples)
- [The future of the sharing business model](https://opensource.com/article/23/4/future-sharing-business-model)

Congratulations, @RonMcFarland! And thanks, as always, to @AmyJuneH and the entire Opensource.com team.

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn
