### ISSUE TITLE
Migrate the editorial Project Classic to the new Project

### ISSUE THREAD

**Issue by jimmysjolund** [open-organization/editorial#155]
I noticed that the Editorial project is going to be sunset and we should migrate to the "new" project if we want to keep the current flow.

> Projects (classic) will be sunset on August 23, 2024
> We encourage you to migrate this project to the new Projects experience. Read more about this sunset in our [changelog](https://gh.io/projects-classic-sunset-notice). Note: Projects must be enabled to migrate.

**Comment by jimmysjolund** [comment]
What do you think @semioticrobotic ?

**Comment by jimmysjolund** [comment]
I just migrated the classic project in OpenOrgTV and it was a quick uneventful change.

**Comment by semioticrobotic** [comment]
Oh, great catch, @jimmysjolund. Yes, please: Let's migrate. If you could initiate, that would be great (I am out on vacation).

**Comment by jimmysjolund** [comment]
Migration done. Everything looked alright after my scan.
