### ISSUE TITLE
Series: Rebuilding of a community series

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/editorial#53]
After a chat with Heidi yesterday, I was inspired by an idea we had - namely, starting a new series about "Rebuilding our community". We were talking about how communities live and breathe and how we'd like to make sure that this next phase of our community helps us address some of the social credit issues we've been dealing with, as well as providing a kind of pipeline for those of us who need more/something different.

Draft of the 1st two pieces started here, and am pinging some folks in discourse

**Comment by HeidiHVL** [comment]
@LauraHilliger i added some comments in the doc for the first post. :) 
see [https://docs.google.com/document/d/1XyFocblLUXkEapSAsj4iYM5r5Dbo6Q3iqQ3BmOyphIo/edit#heading=h.g86no07edilo]

I don't think we need a special blog or anything..... because, if we think about it, the past writing of articles was dictated by our relation to the Brand team, who needed a particular polished quality and process before publishing. But now we are free from some of that formal-ness -- which means we can probably open editing to the Ambassador group (as you are) and then publish! 
What are your thoughts with that/

**Comment by semioticrobotic** [comment]
Love this idea, @LauraHilliger. If we're striking out on an evolutionary journey, we may as well document it!

As we discuss and sharpen your vision, we can begin discussing potential publication outlets.

**Comment by LauraHilliger** [comment]
Oh yes, absolutely want to invite everyone to write, rewrite, make it an ambassador piece. And I think @semioticrobotic 's point about clarifying the whole community is a good one.

**Comment by semioticrobotic** [comment]
Would love to participate! Thanks, @LauraHilliger. Hopefully I'm able to jump back int your document in the next day or two.

We might consider using this space to maintain a list of articles in the series, mirroring the handful of tasks/moments we tend to chronicle in the community evolution. For example:

- Series introduction
- Evolving a governance model
- Rebranding a community
- Building a new community website
- Architecting a robust contributor pipeline
- etc.

... just to give names to some of the "episodes" we'll be recounting as they happen (and also a great way to us to map the path of the community renovation, too!).

**Comment by semioticrobotic** [comment]
Whew! Okay! Thank you very much for your patience, @LauraHilliger, as I was able to carve a bit of time to really digest and contribute some of my own thoughts to the piece. I think it's going to be really great. I made some edits and left some comments for you.

**Comment by LauraHilliger** [comment]
@semioticrobotic so I think post 1 is done, but should we try to finish at least two at a time so that we give ourselves deadlines and use the public series to push us to GSD?

**Comment by semioticrobotic** [comment]
I think your thinking. Perhaps ideally, we'd have three pieces always in various stages of production:

1. Brainstorming
2. Drafting and editing
3. Polishing and submitting

We have a "Phase 3" piece at the moment, and something like a "Phase 1." But maybe we wait until "1" becomes "2" and then submit "3" into the pipeline?

**Comment by semioticrobotic** [comment]
Left some edits and suggestions in the doc for you, @LauraHilliger!

**Comment by LauraHilliger** [comment]
Rearranged the second article, and I think we're moving into Phase 2 there. Would love to have @funnelfiasco 's thoughts as you suggested. See the next steps section – do we actually already have a CoC? Would be cool to have a work-in-progress (or even a finished piece) on the wiki when we publish :)

**Comment by funnelfiasco** [comment]
I will try very hard to take a look in the next day or two

**Comment by semioticrobotic** [comment]
> do we actually already have a CoC? Would be cool to have a work-in-progress (or even a finished piece) on the wiki when we publish :)

We do not! But it's one of the discussions I'd hoped this article would spark. Seems like it will!

**Comment by funnelfiasco** [comment]
LGTM. I suggested a paragraph about emeritus status. I could probably turn that into a full-blown article at some point maybe?

Also +1 to a Code of Conduct.

**Comment by semioticrobotic** [comment]
> I could probably turn that into a full-blown article at some point maybe?

Oh you definitely could.

I'm eager to read the revised version and will leave any comments I have in the next day or two!

**Comment by semioticrobotic** [comment]
As per above: I've created separate issues for Article 1 (#54) and Article 2 (#55) so keeping track of them is a bit easier (for me, anyway).
