### ISSUE TITLE
Scaling community governance

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#55]
Ambassador @LauraHilliger will publish the second installment in her "renovating an energetic community" series (see #53)—this one on evolving a community's governance model.

**Comment by semioticrobotic** [comment]
Love this one, @LauraHilliger/ I made some suggestions in your document and added a bit of additional history (which you are more than welcome to remove if you don't feel it adds enough). And thanks much @funnelfiasco for the great addition describing Emeritus status. Perfect fit.

**Comment by LauraHilliger** [comment]
@HeidiHVL - for sure go leave comments [in the governance section](https://docs.google.com/document/d/1XyFocblLUXkEapSAsj4iYM5r5Dbo6Q3iqQ3BmOyphIo/edit#heading=h.q3vvfuvgbm3x) (or anywhere else of course)

**Comment by semioticrobotic** [comment]
Read through this once more and think it's looking great, @LauraHilliger and @funnelfiasco. Just signal if you'd like to make more changes—or go to press with a target publication date in early July.

**Comment by funnelfiasco** [comment]
:shipit:

**Comment by semioticrobotic** [comment]
This is now in production as "[How an open project's governance model evolves](https://opensource.com/open-organization/20/7/evolving-project-governance)," targeting a July publication.

**Comment by semioticrobotic** [comment]
Just received word that this is scheduled to run July 02, 2020.

**Comment by semioticrobotic** [comment]
Received the following note in my inbox this morning:

> Enjoyed the article on the evolution of the Open Organization's governance model. The article is an interesting look at  how a community's members can help that community morph into something the people who founded the community never considered or expected. Nice work! And nice collaboration between you, Ben, Laura, and the wider 
community.
