### ISSUE TITLE
Rebranding a community

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/editorial#56]
added a section and brain dump to [the working doc](https://docs.google.com/document/d/1XyFocblLUXkEapSAsj4iYM5r5Dbo6Q3iqQ3BmOyphIo/edit#heading=h.99sh7uj14trz) for Scaling community series (#53). As with the rest of the series, y'all are very welcome to brain dump 

Idk if I'm going overboard with the context here. There's plenty to say about design process, so we can refocus this if you all feel it's veering a bit too in the problem territory.

**Comment by semioticrobotic** [comment]
Thanks, @LauraHilliger (I added a link to the series issue in your message, just so new readers can follow along if they'd like, and we can all keep the thread). Hope to read your new work in the next few days.

**Comment by LauraHilliger** [comment]
HELLLO I finally took this a bit further and wrote the Branding piece. I also started the piece after that about attribution – it fell out of the other text, but I'm not sure we want to focus on attribution at all... In any case, would be happy to have other folks contribute to our community series!!

https://docs.google.com/document/d/1XyFocblLUXkEapSAsj4iYM5r5Dbo6Q3iqQ3BmOyphIo/edit#heading=h.99sh7uj14trz

**Comment by semioticrobotic** [comment]
Awesome, @LauraHilliger! I will take a look and add some thoughts for sure. Would love to hear from others, too, who participated in the rebranding process (@jimmysjolund @funnelfiasco @jonasrosland @jenkelchner and others, etc.)

**Comment by funnelfiasco** [comment]
I added some comments and suggestions to the brand section.

**Comment by semioticrobotic** [comment]
This is on my list to review today! Looking forward to it. More soon.

**Comment by semioticrobotic** [comment]
I think it's looking great. I made some edits to the first half, but decided not to continue until we all feel comfortable that we've got the right narrative, framing, and cadence. Then we can polish up the second half.

**Comment by funnelfiasco** [comment]
I like the edits!

**Comment by LauraHilliger** [comment]
I added a lot more edits to the background section – this is the bit we're trying to find the comfortable balance, I think –  and I tried to clear out the other suggestions. I accepted most (except for one because I didn't feel it was true 🐙

**Comment by semioticrobotic** [comment]
Indeed, some hyperbole and historical inaccuracies on my part. Thanks for tempering.

**Comment by semioticrobotic** [comment]
Made a few more edits and extended the narrative a bit, @LauraHilliger. See what you think. I see @jimmysjolund poking around in there too. Excellent.

**Comment by LauraHilliger** [comment]
> Indeed, some hyperbole and historical inaccuracies on my part. Thanks for tempering.

actually the untrue one was @funnelfiasco 😛

**Comment by funnelfiasco** [comment]
> actually the untrue one was @funnelfiasco 😛

I was just BSing in the hopes that I someone would correct me where I was wrong 😁

**Comment by LauraHilliger** [comment]
One little rephrase and I think this is ready to go? https://docs.google.com/document/d/1XyFocblLUXkEapSAsj4iYM5r5Dbo6Q3iqQ3BmOyphIo/edit#

**Comment by semioticrobotic** [comment]
Love how it turned out. Thanks, @LauraHilliger. Going to ask a rep from Open Studio to check it out to, too, before we move forward, but I don't expect that to raise issues (or take long). Will keep everyone posted.

**Comment by semioticrobotic** [comment]
We're all set. I'll get to work adding this to the pipeline.

**Comment by semioticrobotic** [comment]
Due August 9th!
