### ISSUE TITLE
The power of open source during a pandemic

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/editorial#57]
Alexandra Machado and I are drafting this post:
https://docs.google.com/document/d/1X7tPIN6K9IKrr_KfnNp4cnaHfX0mp1Iwj3foOyUMZI0/edit?ts=5f2047cd

Obviously just starting WIP!!!

**Comment by semioticrobotic** [comment]
Neat! Will leave you some in-doc feedback.

**Comment by semioticrobotic** [comment]
Scheduled to appear August 30, 2020!
