### ISSUE TITLE
Open environments are where innovative ideas thrive

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#61]
This is the second article in @RonMcFarland's "Open Organizations and Innovation" series.

**Comment by semioticrobotic** [comment]
Sent to @trncb for editorial review.

**Comment by trncb** [comment]
@semioticrobotic I have reviewed and made just the one suggestion.

@RonMcFarland great article!

**Comment by semioticrobotic** [comment]
Thanks so much, @trncb. This is a huge help. I will get this article into production and offer @RonMcFarland an update soon.

**Comment by semioticrobotic** [comment]
Scheduled to appear November 08, 2020, as "[Open environments are where innovative ideas thrive](https://opensource.com/open-organization/20/11/environments-for-innovation)." Thanks, @RonMcFarland!

**Comment by semioticrobotic** [comment]
Published! Thanks @RonMcFarland (and @trncb!).
