### ISSUE TITLE
A grandfather's lessons in open leadership

### ISSUE THREAD

**Issue by HeidiHVL** [open-organization/editorial#62]
**Background:** 
There are six open management values and we can discuss those that are most interesting given your roles, experience etc.:

1. Champion the open culture
2. Inspire shared purpose
3. Hire, develop, and reward the team 
4. Deliver results through empowerment
5. Make decisions in an open and timely manner 
6. Create an environment of belonging, respect, and mutual support

**Interview Process** 

- We work on this document to pre-define interview questions to make sure we collaborate on the conversation. We might have enough discussion points for 2 separate interview recordings (although we record both during the same BJNs session)
- We schedule a 1-hr Bluejeans conference where we record the interviews 
- Heidi summarizes the interview in the article(s), and adds a link to the recorded interviews
- We review the draft of the article, edits are made, and the article is readied for publication 
- The article is published!! The world becomes a better place!!! 

**Interview Questions**

1. Introductions: Heidi, Bryan and Jos 
2. Tell us how you (Jos) got involved in leading and managing with open values.
3. What does "managing with open values" mean to you? 
4. More... (Heidi to do some background reading)

**Comment by semioticrobotic** [comment]
Tagging @JosGroenNL here so he's aware of the request for an interview!

**Comment by HeidiHVL** [comment]
thanks @semioticrobotic -- I spoke with @JosGroenNL yesterday but didn't know his ID (now I do since you shared it but it doesn't come up as a selection when I type the "at" sign)

**Comment by semioticrobotic** [comment]
> but it doesn't come up as a selection when I type the "at" sign

I _think_ that's because @JosGroenNL hasn't yet accepted the invitation to join the GitHub group. When he does, we'll be able to "at" him. :smile:

**Comment by JosGroenNL** [comment]
Hi all, I'm here alive and kicking!

**Comment by JosGroenNL** [comment]
Hi Heidi, as discussed I think it is nice to pick some items of one of my articles I send this week to talk about and share our thoughts on in the interview

**Comment by JosGroenNL** [comment]
Do I  need to click a "yes" somewhere?


Op 25 november 2020 om 16:23 uur schreef Bryan Behrenshausen <notifications@github.com>:






but it doesn't come up as a selection when I type the "at" sign

I think that's because @JosGroenNL hasn't yet accepted the invitation to join the GitHub group. When he does, we'll be able to "at" him. 😄

**Comment by semioticrobotic** [comment]
Thanks, @JosGroenNL! You're all set.

**Comment by semioticrobotic** [comment]
@HeidiHVL and @JosGroenNL are making this is video-first series of conversations. Will update @jenkelchner when we have the draft footage.

**Comment by semioticrobotic** [comment]
This video is now in production for @jenkelchner review. Some notes from me:

- It could really use a better title and description. I admit that I did not have time to come up with anything more compelling.
- Video requires a title card (apologies again—lacked the time to make and add the card)
- @HeidiHVL and @JosGroenNL have indicated that this conversations video does not require editing.

**Comment by jimmysjolund** [comment]
Is the recording available somewhere?

**Comment by semioticrobotic** [comment]
> Is the recording available somewhere?

It will be soon, @jimmysjolund! @jenkelchner is reviewing the video and preparing it for publication on our new YouTube channel. Release date is at her discretion.

**Comment by jimmysjolund** [comment]
Ok, what I'm wondering is if it will be possible to review before publication? Like in a github repo?

**Comment by jenkelchner** [comment]
@jimmysjolund if you are wanting to be co-editor on projects please let me know.  I'd need to grant you access to the channel and also have a brief discussion.

**Comment by jimmysjolund** [comment]
I'm not sure what co-editor would mean, but as a trained sound engineer I'm curious on sound, EQ, sync with video, etc and perhaps could have input before release?

**Comment by jenkelchner** [comment]
Ah, I see.  Well, we created the most simple process for the Ambassadors to do videos and would not require editing on any front. And to keep videos informal as well. I made a guide in our Ambassador files for the best setup and recording options. 

We can dig more into this on our call next week if you'd like.

**Comment by semioticrobotic** [comment]
@jenkelchner I have updated the video title and description with generous assistance from @HeidiHVL. I also added a card (thank you for the helpful template).

This is ready for your review. I would ask you to please take a look at the beginning, where there's some audio/video glitchiness and blue screening as the interviewers come online. I tried to cut that out, but couldn't figure out how to work the editing tool. Sorry. :frowning_face:

**Comment by jenkelchner** [comment]
@semioticrobotic the processing on the edit will be done shortly and the video will be able to be scheduled. Do you have a schedule date on your end I need to set it to?

**Comment by semioticrobotic** [comment]
No coordinating article on my end! This is our first "video-only" piece. So scheduling is entirely at your discretion.

My typical next step is to send the pre-publication item to the creator for final review (thus my clever name for this column in the board!). Creators can read/watch/review and offer final approval or corrections. This is easier to do with print, so whether to do it with video is your call. It would mean giving creators access to their pre-publication YouTube videos (I think they need certain account permissions—you know better than I do). In the past, I've found this step useful for confirming last-minute details with creators and stakeholders (in the case where authors, for example, have said something like "I need to show the final version to my organization's PR team," or something like that).

When everyone is satisfied, I typically look at what else is already scheduled (see next column in the board) and work around that, to space things out. Then I post the finalized date in the issue conversation (i.e., this thread), tag anyone relevant, and move the card to "Scheduled."

Then we just wait for the proposed date and time to roll around!

Something to discuss with you, @JosGroenNL, and @HeidiHVL: Do we want another column in our editorial process for ``Publicizing``? Cards in this column can go to the attention of community social media account managers (me, @JosGroenNL, @HeidiHVL) and anyone else interested in helping promote. When the tweets are sent or scheduled and the posts posted, we can move the card to ``Published``, considering them "done." Just a thought. We can all converse at a future meeting if you'd like.

**Comment by JosGroenNL** [comment]
He Bryan,

I need your help here. Where can I watch the content? Need to find my way in the portals and systems.

Jos

**Comment by semioticrobotic** [comment]
I *think* @jenkelchner has to get you set up with an account capable of reviewing pre-publication content (or upgrade your YouTube account to be able to do it, or some such thing). Will let her advise us (right now she's on the phone with @HeidiHVL).

**Comment by JosGroenNL** [comment]
👍

Met vriendelijke groet,

Jos Groen

**Comment by jenkelchner** [comment]
Video is live: https://www.youtube.com/watch?v=07YBs0ss9rU

We will need to coordinate any social posting.

**Comment by JosGroenNL** [comment]
Soo cool! Nice piece of work!

**Comment by semioticrobotic** [comment]
[Promoted on Twitter](https://twitter.com/openorgproject/status/1371921051895091204)!

**Comment by semioticrobotic** [comment]
Looks like promoted on LinkedIn, too. Great job, all.
