### ISSUE TITLE
Roundup of the most-read articles in 2020

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#63]
It's an Opensource.com tradition, so I'll pull the data and get started.

**Comment by semioticrobotic** [comment]
Interesting batch this year! Here they are:

1. [The power of open source during a pandemic](https://opensource.com/open-organization/20/8/power-open-source-during-pandemic) (by @LauraHilliger and Alexandra Machado)
2. [Building a community of practice in 5 steps](https://opensource.com/open-organization/20/2/building-community-practice-5-steps) (by Tracy Buckner)
3. [Never enough: Working openly with anxiety](https://opensource.com/open-organization/20/1/leading-openly-anxiety) (by @samuelknuth)
4. [Book review: Nine Lies About Work](https://opensource.com/open-organization/20/4/book-review-nine-lies-about-work) (by @RonMcFarland)
5. [Who is the glue person on your team?](https://opensource.com/open-organization/20/6/glue-person) (by @LappleApple)

**Comment by semioticrobotic** [comment]
The @open-organization/ambassadors bringing the heat, once again. Congratulations to everyone. We'll be publishing this some time over the winter holiday. Specific date coming soon.

**Comment by samuelknuth** [comment]
Cool - it's time for me to come up with something new!

**Comment by semioticrobotic** [comment]
This'll be published December 20, 2020. Headline pending.

**Comment by semioticrobotic** [comment]
Now published as "[5 stories about open principles changing organizations in 2020](https://opensource.com/open-organization/20/12/best-of-2020)."
