### ISSUE TITLE
How to thrive in our changing work environments

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#64]
From @RonMcFarland, the second part of the review of *The Shift*.

**Comment by semioticrobotic** [comment]
Sending to @trncb to see if he has time/capacity to copy edit.

**Comment by semioticrobotic** [comment]
Scheduled to appear Thursday, January 21 as "[How to thrive in our changing work environments](https://opensource.com/open-organization/21/1/thrive-future-work)."

**Comment by RonMcFarland** [comment]
Just read through it.  It looks good to me.  Ron

**Comment by semioticrobotic** [comment]
Thanks, @RonMcFarland. Then we're all set. Great work on this.

**Comment by semioticrobotic** [comment]
[Published!](https://opensource.com/open-organization/21/1/thrive-future-work) Great work, @RonMcFarland. I will get started on editing the third part.
