### ISSUE TITLE
Draft an Open Leadership Definition

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/editorial#67]
We discussed researching and documenting this topic in 2021 strategy session. We want to create a definition of Open Leadership as we did for Open Principles. Other issues to be filed :)
- What is "open" about "open leadership"?
- Ben: I wonder how we might make a low entry point tool that organizations can use to help them take early steps toward being more open? This is especially a desire for learning communities.
- Laura: will dig up the ancient Open Leadership through Opened framework and posts I wrote back in the day

**Comment by semioticrobotic** [comment]
Excellent! First step, I believe, will be tackling #71.

**Comment by shabnoorshah** [comment]
The definitions I found already existing are as follows: 

Red Hat definition "Open leadership is a blend of mindsets, behaviors, and practices that enable people to thrive and contribute in an open organization." 

Mozilla: Open leadership is a set of practices and skills people can use to mobilize their communities to solve shared problems and achieve shared goals.

**Comment by LauraHilliger** [comment]
thanks @shabnoorshah! The "Definition" in this ticket expands towards a framework, like the definition of Open Principles, of which there are 5, and those five are clearly defined. We're seeking to define exactly *what* "mindsets, behaviours and practices" or what that "set of practices and skills" in open leadership are. We have loads of stuff started in this direction. We're looking to collate work from around the open community, do a bit of meta analysis, and see what the global community thinks "open leadership" is. 

Apparently I spent a good 3 months thinking about this right before I left Mozilla in 2015:

- https://www.laurahilliger.com/models/open-fluency/
- https://www.laurahilliger.com/leadership/open-web-leadership/
- https://www.laurahilliger.com/leadership/iterating-organizing-structures/
- https://www.laurahilliger.com/models/collapsing-open-leadership-strands/

And my former Mozilla colleagues took it all way further:

- https://mozilla.github.io/open-leadership-framework/framework/

IMHO, given the pre-existing work on this, we need to circle up in discussion and figure out what exactly we mean by this ticket.

**Comment by shabnoorshah** [comment]
Hi @LauraHilliger 

Thanks for the perspective, background and links.  Brian and I have had some discussions around the topic of "definition". So this is a welcome thread. It's even more heartening to see the development and direction the community is aiming at. Happy to be a part of it. 

I  agree with you that we need to define what those "behaviors, practices, and mindsets" are when we refer to Open Leadership. I'll dive into the links you have shared (thank you!) to get familiar with the thought process and efforts that have already gone into this initiative 

As a side note, while at Red Hat we use the (previously mentioned) definition of open leadership, in my view it is rather broad and doesn't fully capture the essence of open leadership. To your point, our understanding of open leadership is grounded in the community evolved five open organization principles/characteristics. While I'm assuming that the community sees the direct connection between the definition(s) and open org characteristics, it'll be interesting to empirically verify with the community if it's seen the same way unless ofcourse this exercise has already been done.  The reason for this is that I'm wondering if there are other aspects/components related to open leadership that need to be factored in other than open organsiation principles. In my view, it'll be great to have a common/shared, community evolved baseline "definition "  of open leadership just the way we have the open organization principles. Maybe that is a separate conversation and this conversation is existing elsewhere, either way, I'd be interested in participating in this conversation. 

Thanks and talk soon!
Shabnoor

**Comment by semioticrobotic** [comment]
Thanks for this discussion and the links, @shabnoorshah and @LauraHilliger. I'm looking forward to reading them.

The first point from @LauraHilliger's thread-starter—"What's 'open' about 'open leadership'?"—was from me. To my mind, the work of answering this question is the work of composing a definition of open leadership.

Not answering this question means writing a definition of "open leadership" that lacks the kind of specificity the concept would need to differentiate it from leadership in general. For example, take the Mozilla definition @shabnoorshah posted:

> Open leadership is a set of practices and skills people can use to mobilize their communities to solve shared problems and achieve shared goals.

It's a fine definition, but it's really just a definition of ... leadership. "Mobilizing community to solve shared problems and achieve shared goals" is something someone can do in lots of way, including through coercion, command-and-control, etc. That's certainly a form of leadership! But maybe not an open one. So to me, that definition doesn't really define _open_ leadership specifically.

And I therefore agree with @shabnoorshah's point that Red Hat's definition of "open leadership" is also compelling but insufficient on its own. I do like the way that it explicitly links to open organizations (leaning, then, on the Open Organization Definition), but more specificity regarding the particular "behaviors, practices, and mindsets" an open leader demonstrates would be useful (the same goes for the phrase "practices and skills" in the Mozilla definition, which may be outlined somewhere, but I will need to ask a Mozillan).

So this project, I think, is very promising and rather exciting—a step in the direction of actually specifying a collaborative and workable definition of open leadership others can implement, modify, and tweak for their own organizational contexts.

**Comment by chadsansing** [comment]
Hey, All - joining from Mozilla Foundation land. What a compelling and energizing issue & thread! 

@LauraHilliger's link to the Open Leadership Framework provides more detail about the behaviors, practices, and mindsets we identified as key at the time. We also approached the work through our Open Leaders curriculum which eventually split into 2 parallel tracks, one mostly concerned with the ethos of project management and the other with developing cultures that allowed openness and trust to flourish.

- [Project track](https://docs.google.com/document/d/1G_opVoiO1VXlfjs-xvbbHVaF97jZBE3DH-DWxAEqtT4/edit#heading=h.5qlxraoq91j2).
- [Culture track](https://docs.google.com/document/d/1dpH_LPZQ2FTUbK1y1tIDrJfYvesFp3Ivwqp1_jju-5E/edit#heading=h.5qlxraoq91j2).

I think the question of, "What makes this 'open' leadership?", or, "What makes this different from leadership or good leadership?", persists, but that is, indeed, the question. Anyhow, sharing these artifacts in case they're of interest! 

Other useful case studies in adapting open leadership across contexts might include the [OLX programs](https://foundation.mozilla.org/en/initiatives/mozilla-open-leaders/) that came out of our very last round of open leadership training. This was a train-the-trainer, community-hand-off kind of program modeled after [Openscapes](https://www.openscapes.org/), an open science/open leadership program led by a Mozilla Fellow.

I'm excited to follow this conversation as a lot of my day-to-day work now focuses on MozFest. My thanks!

**Comment by semioticrobotic** [comment]
Wonderful to see you, @chadsansing. And thanks so much for providing all this great context. My eyes had slipped right over that final link from @LauraHilliger outlining the specifics of Mozilla's definition. I look forward to reading.

**Comment by chadsansing** [comment]
@semioticrobotic - just keep in mind it's years-old and needs a bit of an update :)

**Comment by samuelknuth** [comment]
Great discussion. Just skimming over the Mozilla material it looks like quite a lot there. That seems to be the kind of the thing I might imagine would come out of this effort (specifically the [framework](https://mozilla.github.io/open-leadership-framework/framework/)). I'd like to read that more closely. 

I am curious though what we want to create from this? How do we envision this being used? I could see it being an academic exercise, which doesn't feel very applicable or useful to me from the perspective of a practicing leader. Or is the goal to create something practical for leaders? To help people become more open leaders?

**Comment by shabnoorshah** [comment]
Great point @samuelknuth , it'll be useful to identify what to focus on and then define the objectives/target outcomes accordingly.  In my view some parts of it could be "academic" (rather rooted in a certain amount of scientific research) for validity to strengthen our arguments, conviction, and confidence, it MUST be something that can largely be practically applied, lived, and experienced by leaders and practitioners in a way that positively impacts individuals, teams and organizations.  Therefore if we choose to incorporate scientific research methods, its purpose would be to test and confirm if something is effective or not. 

@chadsansing, thanks for sharing additional context and links, I'll be going through them over the next few days to understand and appreciate the work that has already gone in and to factor it in in future conversations.

**Comment by semioticrobotic** [comment]
> I am curious though what we want to create from this? How do we envision this being used? I could see it being an academic exercise, which doesn't feel very applicable or useful to me from the perspective of a practicing leader. Or is the goal to create something practical for leaders? To help people become more open leaders?

Discussion at the strategy session highlighted two possible outcomes: a definition and a maturity model (this makes sense, since this group maintains the Open Organization Definition and Open Organization Maturity Model, so we "go there" instictively). These are of course only two options (and they are hefty options), which is why we also opened a separate issue about collecting case studies (#68) to begin the research that would allow us to (inductively) construct something broader.

In response to the above from @samuelknuth, I'd simply argue that creating and maintaining a definition of open leadership is eminently practical, because such a definition would inform our practice(s). That is to say, if we're going to create resources about "open leadership," we need to determine what we are (and are not) talking about. If we're going to help people become open leaders, we need to determine what we are (and are not) going to help them be and do. If we're going to be champions of open leadership, we need to know what we are (and are not) championing.

Here again I turn to the Open Organization Definition as an example. When the Open Organization project kicked off, the Open Organization Ambassadors stressed a critical need to define the very thing we said we were going to be advocates of, stewards for, and practitioners of (open organizations). That definition has guided our practice in critical ways over the past three or four years: it helps us establish editorial policy (what will we and won't we publish articles about?); it sets the agenda for our book series; it provides a framework for arguments and presentations; it's the backbone of our community messaging; it helps us speak and exhibit to others with clarity, precision, and specificity.

This is why I believe the exercise will be important, and tackling it sooner rather than later ensures we're moving in a concerted direction.

**Comment by kattekrab** [comment]
Hi all!

What distinguishes "Open Leadership" from leadership in more general terms is deeply interesting, and challenging.  

Here's another question to consider: Is there anything commonly associated with leadership in general, that is NOT characteristic of Open Leadership and Open Leaders?

For instance, open leaders probably can't depend on positional authority or hierarchical power structures to issue command directives, or expect compliance or participation from contributors who are choosing to commit their time to a course of action.

Elements worth considering:
- Anyone can choose to lead.
- Anyone can choose to leave.

I reached out to Linus Torvalds and Dries Buytaert and asked them both:

**"What does Open Leadership mean to you?"**

Dries pointed me to these blog posts:
- https://dri.es/responsible-maintainers
- https://dri.es/the-job-of-a-drupal-initiative-lead

and Linus said:

> Heh. I don't think in those terms. That's an odd question to me. I don't actually feel that I "lead" the project, although since I'm also clearly not a manager, I might call myself the "technical lead person".
> 
> So I may use the word, but it's not really how I actually see what I do in the project.
> 
> In fact, over the years, I've come to the conclusion that the most important thing I do is basically to "be around" and help be part of the framework keeping things on a reasonably even keel. 
> 
> "The project leads itself - the "leadership" doesn't come from me saying "now we're going in this direction and doing this". No, what I do is perhaps more of a "shepherding" or "stewardship" than any kind of "leadership".
> 
> Put another way, I'm a curator of the project, not really a "leader".
> 
> And the most important part of curatorship is to allow the project its own life, while also giving it enough stability that it doesn't fragment or go off in completely crazy directions."

Wouldn't it be amazing if we could ask this simple question of people in the communities we're involved in, and see what we learn? The conversation itself would be fascinating!

**Comment by semioticrobotic** [comment]
> Wouldn't it be amazing if we could ask this simple question of people in the communities we're involved in, and see what we learn? The conversation itself would be fascinating!

Thank you for this, @kattekrab!

I want to think on it a bit more, but did want to quickly point you to the Open Leadership interview series that OpenOrg Ambassador Heather Leson is spearheading, which to a large extent does what you're suggesting above! You'll see the first piece in the [editorial queue](https://github.com/open-organization/editorial/projects/1).

**Comment by kattekrab** [comment]
Oh that sounds wonderful.  I'll take a look! Thanks @semioticrobotic

**Comment by samuelknuth** [comment]
@semioticrobotic thank you - your explanation makes sense to me!

**Comment by kattekrab** [comment]
At linux.conf.au this weekend, I took this screenshot during @tobybellwood's talk 

Open Leadership
 - Always be looking for transparency
 - Be open to suggestion & correction
 - Embrace failure
 - Understand diversity
 - Become a "lifelong learner"

<img width="1438" alt="Open Leadership - TobyBellwood - 2021-01-25 at 14 34 46" src="https://user-images.githubusercontent.com/172755/105808645-36c1cd00-5ffc-11eb-8dcc-4dd0e3dc0720.png">

**Comment by semioticrobotic** [comment]
Also want to leave a notes about the excellent [Awesome Leadership and Management](https://github.com/LappleApple/awesome-leading-and-managing) list, curated by our own @LappleApple. Lots of great grist there.

**Comment by LauraHilliger** [comment]
Saw this from @wiobyrne and made a note-to-self to post to this thread because I know he's quite open :)

https://wiobyrne.com/leadership-roles-skills-and-you/

**Comment by wiobyrne** [comment]
Thank you for pinging me @LauraHilliger. This has me thinking a bit about leadership and open. 

I wrote [this piece](https://wiobyrne.com/moving-toward-transparency-in-higher-education/) with a colleague a couple of years ago as our department was closing up. Looking at transparency of mission, action, metrics, and stakeholders. 

Still unpacking all of the great stuff you all shared. More to come. :)

**Comment by semioticrobotic** [comment]
Wow! Thanks for this great link, @wiobyrne. I hope this is not too forward, but I feel compelled to ask: Would you consider submitting this (or a version of this, if you'd like to update/revise) for our community's [*Open Organization Guide for Educators*](https://github.com/open-organization/open-org-educators-guide)? I think it'd be a fantastic addition to that book (pinging book editor @engineerteacher to assess and confirm).

Done hijacking the thread! Thanks for considering, @wiobyrne.

**Comment by wiobyrne** [comment]
Hi all, @semioticrobotic I think I could revise the piece for the guide. Let me know the next steps.

In terms of this thread, I'll keep thinking/looking through old ideas. The piece that I shared (and the one that @LauraHilliger shared) focuses on different levels of leadership. That is, the viewpoint from the one leading to the viewpoint of someone in the group/organization. 

There is also the perspective of open leadership when you consider a user of a product. I think there is a need (or users should demand) transparency and leadership when using an app or platform. As an example, with hacks and data breaches, there should be a pattern set in place where leaders make the hard choices, and provide as much transparency as possible.

I've also lately been thinking more about open in spaces where trolling, outing, and abuse happens in digital spaces. I'm wondering if there is a need for local/global aspects of open and transparency in leadership.

**Comment by semioticrobotic** [comment]
(Thanks, @wiobyrne! Created [a new issue](https://github.com/open-organization/open-org-educators-guide/issues/40) for us.)

**Comment by waisean** [comment]
> As an example, with hacks and data breaches, there should be a pattern set in place where leaders make the hard choices, and provide as much transparency as possible.

Off topic to this thread, I've done a little thinking on this recently, with hopes of doing more and maybe trying to write something or throw a talk together around InfoSec and Open Orgs/ODF, though I need to do a lot more reading and diving into things like the OSSF and OISF to see what they've generated. I think there's room around what they've done with regards to how a security team can operate openly while also maintaining the necessary level of discretion. This could somewhat fit into a leadership discussion, or also a general "open security org" type thing.

> 
> I've also lately been thinking more about open in spaces where trolling, outing, and abuse happens in digital spaces. I'm wondering if there is a need for local/global aspects of open and transparency in leadership.

A good topic to bring in here might be points around maintainers and leaders in open projects and protecting themselves while remaining open. A lot of maintainers take a lot of abuse, [this thread on recent changes in pyca](https://github.com/pyca/cryptography/issues/5771) is an good example. From the leader/maintainer side, how to introduce controversial changes, when to block bad apples and potential recourse for those bad apples, keeping afloat during the inevitable waves that will come after such a change, and so on. It could also have an approach from the user/downstream side and how to raise concerns appropriately without starting a flame war or burning maintainers out.

**Comment by semioticrobotic** [comment]
> Off topic to this thread, I've done a little thinking on this recently, with hopes of doing more and maybe trying to write something or throw a talk together around InfoSec and Open Orgs/ODF, though I need to do a lot more reading and diving into things like the OSSF and OISF to see what they've generated. I think there's room around what they've done with regards to how a security team can operate openly while also maintaining the necessary level of discretion. This could somewhat fit into a leadership discussion, or also a general "open security org" type thing.

Love this idea, @waisean! Something along the lines of "Who says open organizations can't have secrets?" would be a nice piece—particularly for the [Guide to IT Culture Change](https://opensource.com/open-organization/resources/culture-change).

**Comment by semioticrobotic** [comment]
Today @HeidiHVL held a great information/planning session concerning this work, and discussion was both lively and productive. We [recorded our chatter](https://bluejeans.com/s/EJc8avxIxGX/) and all are welcome to review, comment, and participate.

**Comment by LauraHilliger** [comment]
Feel like the ThinkSpace document is starting to be an answer to this ticket...not sure if it's linked above, but here's where this is starting to form: https://docs.google.com/document/d/1F8pxpbnkJLPzw3bHAxm5tZD6zksDagWZIh724t17cmU/edit#

**Comment by semioticrobotic** [comment]
Thanks, @LauraHilliger. Anyone seeking access can ping me and I'll provide it. The goal here is to create a sketch/architecture—however tentative and drafty—and get it into a more open place with fewer barriers to contribution from a wider group.

**Comment by LauraHilliger** [comment]
Hi everyone! We've been making loads of progress on the Open Leadership Definition and could use more feedback. I've only just penned a first draft for Adaptability and am happy for any input, especially if you have ideas for more think/act points. Cross posting to our community forum ;)

https://docs.google.com/document/d/1F8pxpbnkJLPzw3bHAxm5tZD6zksDagWZIh724t17cmU/edit#heading=h.t6o900b0dybk

**Comment by semioticrobotic** [comment]
We've now got a "public beta" open and ready for comment. It's in [a shared folder](https://drive.google.com/drive/folders/1e1N_0p5lJEwAo_s6hQ3OK0KaJIfc7fgF?usp=sharing). We'll be formally announcing the beta release and calling for participation on June 02 (our community anniversary!).

**Comment by semioticrobotic** [comment]
And now we've [officially announced the public draft](https://opensource.com/open-organization/21/6/celebrate-sixth-anniversary)! Thanks, everyone, for your great work so far. I'm eager to see the feedback we receive.

**Comment by engineerteacher** [comment]
Awesome!

Cheers,

-Ben

Ben Owens

*Co-Founder & Lead Innovation Engineer*
*Open Way Learning* <http://openwaylearning.org/>
706.878.8946
*Co-Author of Open Up, Education!
<https://www.amazon.com/Open-Up-Education-Learning-Transform/dp/1475842007/ref=tmm_pap_swatch_0?_encoding=UTF8&qid=&sr=>
*
* | **National Faculty - PBLWorks
<https://www.pblworks.org/author/ben-owens> | Open Organization Ambassador
<https://opensource.com/users/engineerteacher>*
*Connect: @engineerteacher <https://twitter.com/engineerteacher>, Linkedin
<https://www.linkedin.com/in/ben-owens-0a8a9875/> or Calendly
<https://calendly.com/ben-openwaylearning>*

**Comment by semioticrobotic** [comment]
It is indeed awesome, @engineerteacher! Great feedback so far, too. Lovely to see.

**Comment by semioticrobotic** [comment]
Since we've officially announced [a public draft of the work](https://drive.google.com/drive/folders/1e1N_0p5lJEwAo_s6hQ3OK0KaJIfc7fgF), I think we can close this issue and continue discussion in #93, where we're reviewing and editing that draft. So glad to see this moving along productively. All editorial feedback and assistance welcome!
