### ISSUE TITLE
Write a mission/vision statement for Open Leadership Definition work

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/editorial#71]
or purpose statement, defining what we're aiming at

**Comment by LauraHilliger** [comment]
Perhaps we revisit (from me, @jenkelchner and Heidi) our Open Leadership book ideas
https://docs.google.com/document/d/1xEUHkXdnWvYM6cATJGOaEIra_9SAASFY5kCNDoGfVyQ/edit?ts=5ccc3135#heading=h.jtmee0f99ai3

**Comment by semioticrobotic** [comment]
Some additional context from the 2021 strategy session: The group identified "open leadership" as a shared area of interest and suggested exploring a longer-term project to research and draft something like an "Open Leadership Definition." Before we did that, however, we thought we might benefit from drafting some kind of shared "vision" for the effort—a kind of abstract or unifying overview that articulates the perceived problems and our solutions.

**Comment by ruhbehka** [comment]
I have something like this that a colleague wrote. Let me poke him and see
if he'd interested in getting involved and sharing what he drafted a few
years ago. :)

**Comment by semioticrobotic** [comment]
I've tried my hand at [a first draft](https://docs.google.com/document/d/1EXJunORV0pGuisrc3bcU4-0G8RKkLmOMqN8h4vTqK1g/edit?usp=sharing). While I can't say I'm _super_ jazzed about anything I've managed to produce, I do think it's useful grist for further collaboration. Anyone welcome to take a look.

**Comment by LauraHilliger** [comment]
Nice start. I added some comments and ideas. Perhaps we can add to the agenda today...

**Comment by semioticrobotic** [comment]
I think we've got it! Great work, everyone. All of this messaging is now collected in our ongoing [document of promotional materials and collateral](https://docs.google.com/document/d/1EXJunORV0pGuisrc3bcU4-0G8RKkLmOMqN8h4vTqK1g/edit#).
