### ISSUE TITLE
Elevating open leaders by getting out of their way

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#78]
Incoming article from @JosGroenNL in his series on open organizations and talent management. Will include video component.

**Comment by semioticrobotic** [comment]
Edited and back to @JosGroenNL for review. I made some basic line edits, shuffled a few paragraphs, and posed one or two comments/questions for @JosGroenNL in the margins.

**Comment by semioticrobotic** [comment]
Reviewed @JosGroenNL edits and awaiting final approvals to move to production.

**Comment by semioticrobotic** [comment]
Scheduled for publication on March 25, 2021.

**Comment by semioticrobotic** [comment]
[Published!](https://opensource.com/open-organization/21/3/open-spaces-leadership-talent) Nice work, @JosGroenNL,

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Promote on Discourse
- [ ] Promote on Twitter
- [ ] Promote on LinkedIn

**Comment by semioticrobotic** [comment]
Looks like @JosGroenNL promoted this, too! All set. Great job, team.

**Comment by JosGroenNL** [comment]
Yes I did on LinkedIn!

Met vriendelijke groet,

Jos Groen
