### ISSUE TITLE
To be an open leader, listen to your heart

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#79]
Incoming article from @JosGroenNL in his series on open organizations and talent management. Will include video component.

**Comment by semioticrobotic** [comment]
Draft edited, and back with @JosGroenNL for review.

**Comment by semioticrobotic** [comment]
Second draft edited and back with @JosGroenNL for second review.

**Comment by semioticrobotic** [comment]
This is now in production with Opensource.com.

**Comment by semioticrobotic** [comment]
Scheduled for publication April 09, 2021.

**Comment by semioticrobotic** [comment]
[Published](https://opensource.com/open-organization/21/4/open-leadership-listen-heart)! Great work, @JosGroenNL.

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Promote on Discourse
- [ ] Promote on Twitter
- [ ] Promote on LinkedIn

**Comment by JosGroenNL** [comment]
Thanks for your good work and commitment to get the best out of it!

Jos

**Comment by HeidiHVL** [comment]
I promoted on linkedin but i don't know how to change BB's little check box in his list!

**Comment by semioticrobotic** [comment]
Looks like we got it! Thank you so much for promoting! Looks like this one's in the bag.
