### ISSUE TITLE
To nurture open leaders, managers must learn to let go

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#81]
Incoming article from @JosGroenNL in his series on open organizations and talent management. Will include video component.

**Comment by semioticrobotic** [comment]
Edited and sent to @JosGroenNL for review.

**Comment by JosGroenNL** [comment]
Tx, read it and made some notes to work on later this weekend….

Jos

**Comment by semioticrobotic** [comment]
Typeset and undergoing final review.

**Comment by semioticrobotic** [comment]
Scheduled to publish on June 11, 2021.

**Comment by semioticrobotic** [comment]
[Published](https://opensource.com/open-organization/21/6/nurture-leaders-let-go)! Congratulations, @JosGroenNL.

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn
