### ISSUE TITLE
Sustainable economic development begins with open thinking

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#84]
First article in a new series on open organizations and sustainable development from Ron McFarland.

**Comment by semioticrobotic** [comment]
I've just finished the first round of editorial work with @RonMcFarland and sent the piece to @trncb for additional copyediting help.

@jenkelchner, @RonMcFarland will be recording a short video presentation to accompany this. Please let us know if you have any guidance! Otherwise, we'll simply plan on calling each other, talking through it, and recording.

**Comment by jenkelchner** [comment]
@semioticrobotic @RonMcFarland - the Guide I've put together should give you some tips to help make it easy and smooth.   Whoever is holding the recording, can follow the upload steps posted in the guide. We can sync up from there on schedules and any need edits etc!!

**Comment by semioticrobotic** [comment]
Roger that! We will do our best to make you proud.

**Comment by trncb** [comment]
@RonMcFarland @semioticrobotic I have made my first pass at the first article. If you could review that would be great, thanks.

**Comment by semioticrobotic** [comment]
Really great work on this, @trncb. Thanks so much. I reviewed and accepted the revisions, but will let @RonMcFarland respond to your comments. Then I think we're all set. @jenkelchner: @RonMcFarland and I have a video recording session on the calendar.

**Comment by semioticrobotic** [comment]
This is now [in production](https://opensource.com/open-organization/21/3/sustainable-development-environment) and awaiting video recording.

**Comment by semioticrobotic** [comment]
Okay, @jenkelchner! We did it!

We had to stop and restart a few times (maybe four or five?) due to some flubs from the host (read: me) and dropped connections. But we tried to cleanly and clearly indicate the breaks so they're easy for you to edit around.

The video is rendering as I type this and will drop in your inbox ASAP.

**Comment by semioticrobotic** [comment]
@RonMcFarland and @semioticrobotic re-recorded the video and the second iteration is much better than the first. Currently preparing video for @jenkelchner and a little assistance editing the beginning and end, to remove our setup and clean up our conclusion.

**Comment by semioticrobotic** [comment]
Okay, @jenkelchner!

@RonMcFarland and I have prepared the video component of this article for your review and signoff.

We need a little help trimming the beginning and end of the video (to remove our setup and banter).

It's [right here](https://youtu.be/L_YiiA0J7JM).

**Comment by semioticrobotic** [comment]
I know I need to get better at using the basic YouTube editing tools, so I tried my hand at trimming the beginning of this video. It's processing now. Will have @jenkelchner check my work when it's all done. :smile:

**Comment by semioticrobotic** [comment]
Question for @jenkelchner: Do you think you will have time to review/finalize/approve the video portion of this piece by some time next week? Would be great to publish, as we currently have nothing else on the calendar then. If not, no worries.

**Comment by jenkelchner** [comment]
Apologites I'm not receiving my notifications from here at all. Will do a reset on my github things.  I can try to get this done today ...

**Comment by jenkelchner** [comment]
@semioticrobotic - this has been pushed to public and ready for a go.... 

https://youtu.be/L_YiiA0J7JM

**Comment by semioticrobotic** [comment]
No apologies necessary, @jenkelchner. We really appreciate your taking a look and helping ensure that we're going out with our best foot forward.

Moved back to scheduling because we're planning to "dual launch" both the article and the video. Great to see that the video is now public, because it'll be ready to go as soon as we post the article. I will work with the team to get it scheduled right away.

**Comment by semioticrobotic** [comment]
Schedule to appear Friday, April 23, 2021 as part of a special series marking Earth Day.

**Comment by RonMcFarland** [comment]
Jen,

Thanks for that link.  I might want to share the article and the
presentation separately, as some people just don't like to read all that
much.

Ron

**Comment by semioticrobotic** [comment]
[Published today!](https://opensource.com/open-organization/21/3/sustainable-development-environment) Great work, @RonMcFarland.

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Promote on Discourse
- [ ] Promote on Twitter
- [ ] Promote on LinkedIn
