### ISSUE TITLE
Human at a Distance | Book Promo 

### ISSUE THREAD

**Issue by jenkelchner** [open-organization/editorial#87]
Create a short promo via roundtable chat on the latest Open Org guide Human at a Distance.  

Would like to coordinate with key contributors on the book, top tips and process that would get more eyes on the work. 

Recording Date: March 24 2021 10AM EST
Release Date: estimate April 1 2021

@LauraHilliger @semioticrobotic and any other key contributors

**Comment by jimmysjolund** [comment]
If we can find a suitable time I'd interested!

**Comment by semioticrobotic** [comment]
Making sure to put this on @amatlack and @anupama23-tec radar, because I bet they'd love to join, too.

Seems like you've got this one covered, but I'm happy to act as a stand-in if needed.

**Comment by amatlack** [comment]
Sure, happy to contribute if you need additional folks!

**Comment by jenkelchner** [comment]
Thanks everyone - love this list of folks.  Can we begin to coordinate a time for 30-45 mins in the next 2-4 weeks? I will throw out that Wednesday mornings work (potentially) and early morning EST.  That is if I'm going to moderate.  If Bryan can moderate and record, that is also an option.

**Comment by funnelfiasco** [comment]
Let's fill out this [WhenIsGood](https://whenisgood.net/td84kz5) to figure out a time that'll work. Wednesday mornings tend to be awful for me :-)

**Comment by funnelfiasco** [comment]
Well it seems @semioticrobotic and @LauraHilliger have mutually exclusive schedules. Meetings are hard!

@jenkelchner @jimmysjolund @amatlack if you can [indicate your availability](https://whenisgood.net/td84kz5) we can try to come up with the least-bad time.

**Comment by amatlack** [comment]
@funnelfiasco done! not sure it's helpful though :)

**Comment by semioticrobotic** [comment]
> Well it seems @semioticrobotic and @LauraHilliger have mutually exclusive schedules. Meetings are hard!

Ha! I'm not surprised. Please don't let me be the blocker. I can gladly sit this one out, removing some constraints so @LauraHilliger can participate.

**Comment by jimmysjolund** [comment]
Not much availability for me such times and sadly it changes by the minute.

**Comment by semioticrobotic** [comment]
Additionally, if you'd like me to, rather than participating in the panel itself, I can commit to recording, say, a two- or three-minute introduction that explains the book, the series, the context, the process, etc., and previews the panel itself, so ya'll don't need to do that kind of setup and can just get right to the discussion. Just a thought.

**Comment by funnelfiasco** [comment]
Based on the feedback, I propose Wednesday 24 March at 10am Eastern Daylight Time. Can you moderate then, @jenkelchner ?

**Comment by LauraHilliger** [comment]
Great! I've made a note in my calendar already so it doesn't get scheduled over, but please do someone send an invite when we're confirmed :)

**Comment by semioticrobotic** [comment]
Noice. Able and willing. Looking forward to it.

**Comment by jenkelchner** [comment]
Yes, let's set this one up and I'll send out the invite!

**Comment by semioticrobotic** [comment]
I will update the March report to include this publication!

**Comment by semioticrobotic** [comment]
https://twitter.com/allisonsm7/status/1376883578802429958

**Comment by semioticrobotic** [comment]
Looks like this one's a wrap. Awesome collaboration, team!
