### ISSUE TITLE
 Balancing People and Business (Open Leadership Conversations, Jos Groen Part 2)

### ISSUE THREAD

**Issue by HeidiHVL** [open-organization/editorial#88]
Second interview for youtube with Jos Groen in the Open Leadership Conversations playlist. @jenkelchner @semioticrobotic (FYI)

TBD: 
- [x] Title
- [x] Description
- [x] Bio
- [x] Links
- [x] Hashtags
- [x] Slide thumbnail

**Comment by HeidiHVL** [comment]
TITLE
Balancing People and Business, Open leadership conversations
Jos Groen part 2

io - whatever was used before in part 1. Tag me if you need new/whatever. 

Description
Heidi Hess von Ludewig continues her conversation with Jos Groen about open leadership and the need to balance people and business. 

The slide thumbnails are here in google drive
https://docs.google.com/presentation/d/1agnwoNVR3vN4lf6tSGKt4fxoPKfma_jCWBU8J_Tl-Hc/edit?usp=sharing

Hashtags
#openleadership #openorg 

Link to 256mg video is here 
https://drive.google.com/file/d/1uSdbZgIsD6QWXykoVkBMgtaa1nvhNmQj/view?usp=sharing

Let me know how I did on following the process so I can improve where necessary @jenkelchner @semioticrobotic

**Comment by JosGroenNL** [comment]
He Heidi,

Great work again! I’m exited about it and feel an happy feeling thinking about continuing this series if the time is right.
When will this be published?


Jos

**Comment by semioticrobotic** [comment]
Great! Scheduling for all multimedia publications is at @jenkelchner discretion, so I will leave that question to her.

**Comment by jenkelchner** [comment]
Sorry guys, I had no notification - I'll adjust my github pushes for next time. I'll drop this in my queue!

**Comment by jenkelchner** [comment]
This video is in a editing/processing mode on YT. it will complete within a few hours and it will then be public/live.  Feel free to move forward.  https://www.youtube.com/watch?v=qkskAAyFgz8

@HeidiHVL thank you for the information this time that really helped move that aspect through the hoops.  Still prefer everyone uploads direct to YT a as long term process solution as it takes up my resources / time to do so. However.....this was very seamless and easy to get the edit finalized for you!  :)

**Comment by semioticrobotic** [comment]
Nice! Thanks, @jenkelchner.

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Announce on Discourse (@jenkelchner)
- [ ] Announce on Twitter (@semioticrobotic)
- [ ] Announce on LinkedIn (@JosGroenNL)

**Comment by HeidiHVL** [comment]
@jenkelchner Oh that's right - upload directly!! :) okey dokey! I will remember for next time!

**Comment by semioticrobotic** [comment]
@jenkelchner and @JosGroenNL: Would you be able to announce/promote this one on your respective channels so we can wrap this card this week? No preference for the day—just some time before Friday, when we're slated to publish our next piece.
