### ISSUE TITLE
Modeling open management practices

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#89]
This will be the second piece in @HeidiHVL's interview series with @samuelknuth. It's part of the ongoing  "Managing with Open Values series."

**Comment by semioticrobotic** [comment]
Draft completed and under revision.

**Comment by HeidiHVL** [comment]
woot woot

**Comment by semioticrobotic** [comment]
Off to @samuelknuth for review before we go to production.

**Comment by semioticrobotic** [comment]
Scheduled for publication on September 28, 2021.

**Comment by semioticrobotic** [comment]
[Published today](https://opensource.com/open-organization/21/9/modeling-open-management)! Congratulations, @HeidiHVL and @samuelknuth.

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn
