### ISSUE TITLE
Building open organizations to make a better life more sustainable for everyone

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#90]
Next piece from @RonMcFarland in his series on open organizations and sustainable development.

**Comment by semioticrobotic** [comment]
@RonMcFarland and I have finished our drafting and I've asked @trncb if he'd have a moment to review for us.

**Comment by trncb** [comment]
I have reviewed and made some comments and suggestions. 

Another great piece by @RonMcFarland

**Comment by semioticrobotic** [comment]
Thank you :pray:, @trncb, as always! A huge help.

**Comment by semioticrobotic** [comment]
Astute notes and corrections from @trncb (as usual). We're ready for production now and I'll get right on it next week.

**Comment by RonMcFarland** [comment]
Bryan,

Sounds good.  Let me know when you're ready for the presentation on that
material.  Have a look at the speaker's notes, and we can discuss how we
would like to present it.

Ron

**Comment by semioticrobotic** [comment]
Thanks, @RonMcFarland. I will certainly look them over. It looks like you want to do this one "interview-style" again, as we did last time. If that's the case, I can send you a note about some times we might schedule a recording session.

**Comment by RonMcFarland** [comment]
Hi Bryan,

Yes, I think a 2-way discussion is more interesting than me just talking.
Actually, it would be nice if we had small discussions on each slide.   I
think I have questions in the "Speaker's notes", so you can plan your
questions.  Then, we can have a nice flowing discussion.

Ron

**Comment by semioticrobotic** [comment]
Working on scheduling recording session with @RonMcFarland.

**Comment by RonMcFarland** [comment]
Very good.  May 3rd at 9pm (Japan Time) is fine for me.

Ron

**Comment by semioticrobotic** [comment]
Ron and I have recorded the video component of this package. I am about to upload and render it and will ping @jenkelchner for review when done. Later this week, I will typeset the article.

**Comment by semioticrobotic** [comment]
The video is uploaded and rendering now. By the time they see this, @RonMcFarland and @jenkelchner should [be able to review it](https://youtu.be/lqwkjzraAXw).

**Comment by semioticrobotic** [comment]
The article is now also typeset. Ron should be able [to review it if he'd like](https://opensource.com/open-organization/21/5/sustainable-development-human-impacts).

**Comment by jenkelchner** [comment]
@RonMcFarland @semioticrobotic - video is all good to go and is now public:   https://www.youtube.com/watch?v=lqwkjzraAXw

**Comment by semioticrobotic** [comment]
We don't yet have a publication date for this article, but I don't think keeping the video public while we wait for the package to be published is a problem. Thanks, @jenkelchner, for your help.

**Comment by semioticrobotic** [comment]
Scheduled for publication on May 13.

**Comment by RonMcFarland** [comment]
Thanks!

**Comment by semioticrobotic** [comment]
Published today! Thanks, @RonMcFarland.

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Promote on Discourse
- [ ] Promote on Twitter
- [ ] Promote on LinkedIn
