### ISSUE TITLE
Ask the Ambassadors EP02

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#91]
Episode answers this question:

> I’ve heard the best way to spark the kind of culture change that can lead to a more open organization is to find allies in the organization and partner with them. What strategies do you recommend for doing this? How can I seek out others who want to drive change?

**Comment by semioticrobotic** [comment]
Episode recorded featuring @jenkelchner, @funnelfiasco, and @semioticrobotic. Under review with @jenkelchner now.

**Comment by jenkelchner** [comment]
@semioticrobotic this is in YouTube now ready to be scheduled for viewing based on the community needs.

**Comment by semioticrobotic** [comment]
Awesome. Thanks, @jenkelchner. Let's confer at the next community meeting and set some publications deadlines.

**Comment by jenkelchner** [comment]
@semioticrobotic scheduled for publication on May 19 2021
link will be: https://www.youtube.com/watch?v=zSULnwjOSWg

**Comment by jenkelchner** [comment]
Ready to promote:
- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn

**Comment by semioticrobotic** [comment]
[Tweeted](https://twitter.com/openorgproject/status/1394990464579907587)! Love this episode, @jenkelchner. Great job.
