### ISSUE TITLE
Ask the Ambassadors EP03

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#92]
Episode answers this question:

> When people in my organization hear “open,” they think “no rules” or “anything goes.” But is this true? And if it isn’t, how can I help people understand the relationship between openness and rules?

**Comment by semioticrobotic** [comment]
Episode recorded featuring @jenkelchner, @funnelfiasco, and @semioticrobotic. Under review with @jenkelchner now.

**Comment by jenkelchner** [comment]
@semioticrobotic this is in YouTube now ready to be scheduled for viewing based on the community needs.

**Comment by semioticrobotic** [comment]
Looking great. We'll chat and choose the best date and time to go live.

**Comment by jenkelchner** [comment]
@semioticrobotic this is scheduled to publish on May 26 2021 
Link will be: https://www.youtube.com/watch?v=VdK1-5dHieg

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn
