### ISSUE TITLE
Review community feedback on Open Leadership Definition

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/editorial#93]
Consider audiences for the OLD (can we call it OLD!?) and revise definition for various readabilities. Make this accessible to a wider audience.

**Comment by LauraHilliger** [comment]
@semioticrobotic that wasn't meant as a criticism on your awesomeness! I just used the Hemingway app on the Adaptability session and thought "Hm, we're all smartie pantses" 😘

**Comment by semioticrobotic** [comment]
Re-engaging this thread and this discussion to piggyback on our work revising the OLD in response to excellent community feedback.

We've [compiled a spreadsheet(https://docs.google.com/spreadsheets/d/1ETyMtoNK9MpkTOm2wUvqBBtcnf1S6wGWOUPvOYFyrx8/edit?usp=sharing) charting the work ahead. Please follow along and hop in!

**Comment by semioticrobotic** [comment]
I think our revisions to [the public working draft](https://docs.google.com/spreadsheets/d/1ETyMtoNK9MpkTOm2wUvqBBtcnf1S6wGWOUPvOYFyrx8/edit?usp=sharing) began the work of simplifying the language and making the definition sound more straightforward. I recognize we'll have more work to do as we receive even more feedback, but think I'll close this for now as we plod along to a release date for v1.0.
