### ISSUE TITLE
A more sustainable future should be a more open future

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#95]
This will be the third and final article in @RonMcFarland  series on open organizations and sustainable economic development. It concerns governance of potential open organizations dedicated to this cause.

Will feature a video component.

**Comment by semioticrobotic** [comment]
Now edited and returned to @RonMcFarland for review.

**Comment by semioticrobotic** [comment]
Article revised and entering production. @RonMcFarland and @semioticrobotic to record final video session in this series.

**Comment by semioticrobotic** [comment]
We've recorded this video and I'll be processing it for @jenkelchner review soon.

**Comment by semioticrobotic** [comment]
Article is typeset and video is currently rendering. I'll update this issue with links for @RonMcFarland and @jenkelchner review.

**Comment by semioticrobotic** [comment]
Okay!

### Links

- [Article](https://opensource.com/open-organization/21/6/open-future-sustainable-future)
- [Video](https://youtu.be/iDdcG40PyEY)

@RonMcFarland, I'll be writing the usual email to connect with the Opensource.com editorial team. @jenkelchner the video is ready for your review. I was able to (I think) edit the beginning, but could use your assistance with the end (cutting at the appropriate time, adding the links you usually do, etc.).

Otherwise, I think we're looking good. Nice work, all.

**Comment by semioticrobotic** [comment]
Schedule for publication on June 17, 2021.

**Comment by jenkelchner** [comment]
@semioticrobotic @RonMcFarland - video is finalized and set to publish on June 16, 2021 (3AM EST).

**Comment by semioticrobotic** [comment]
You rock! Thanks, @jenkelchner!

**Comment by semioticrobotic** [comment]
Noting here @jenkelchner great idea to re-promote all videos from this series when we publish this final installment on June 17. @semioticrobotic to queue up some tweets. @JosGroenNL may also participate.

- [First article/episode](https://opensource.com/open-organization/21/3/sustainable-development-environment)
- [Second article/episode](https://opensource.com/open-organization/21/5/sustainable-development-human-impacts)

**Comment by JosGroenNL** [comment]
He Bryan,

Do you want me to contribute to this article?

Met vriendelijke groet,

Jos Groen

**Comment by jenkelchner** [comment]
Hey @JosGroenNL  - we talked at the meeting yesterday about ensuring we re-promote articles in series before the next one drops.  I believe you have an upcoming article in a series and I think Bryan is suggesting yours are promoted on social media as well.

**Comment by JosGroenNL** [comment]
Great idea. I didn’t understand it directly, excuse. I just posted an article of Ron today. We keep moving forward and post an article every week.

Met vriendelijke groet,

Jos Groen

**Comment by RonMcFarland** [comment]
Jos,

The final article on Sustainable Economic Development will be on June 17th,
Stateside.  After that, I shouldn't have anything until July, I would guess.

Ron

**Comment by semioticrobotic** [comment]
Thanks, @jenkelchner, for clarifying my hastily written notes. Yes, @JosGroenNL, the request is that we re-promote some of @RonMcFarland's series before the final piece drops on June 17. @jenkelchner noted that @RonMcFarland's videos are currently the most-watched videos on our channel, so we figured we'd try to give them some extra attention. Thanks for helping on LinkedIn!

**Comment by semioticrobotic** [comment]
[Video published](https://www.youtube.com/watch?v=iDdcG40PyEY)! (Thanks, @jenkelchner!)

**Comment by semioticrobotic** [comment]
And [article published](https://opensource.com/open-organization/21/6/open-future-sustainable-future)! Way to go, @RonMcFarland. Thanks for a great series.

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn

**Comment by JosGroenNL** [comment]
LinkedIn, ✅
