### ISSUE TITLE
New ways to learn about open organizations

### ISSUE THREAD

**Issue by LauraHilliger** [open-organization/editorial#96]
Drafting a post for opensource.com about our anniversary. Pointing to various channels...

**Comment by semioticrobotic** [comment]
Happy to assist if you would like, @LauraHilliger. Also happy to step aside if you would like. Whatever you need. Thanks for kicking this off.

**Comment by LauraHilliger** [comment]
@semioticrobotic literally just started, happy to cowrite!! https://docs.google.com/document/d/1Oji3av4WQliq8pJiGNewPEhzcHvjrXRZsHiS5yL5YYc/edit

**Comment by LauraHilliger** [comment]
OK, I've got a first draft. Feel free to tear it apart. I integrated something about Open Leadership, and I'm not sure that's what we wanted. Needs an ending anyhow, and I didn't include history (but maybe we want to point to https://opensource.com/open-organization/scaling-the-openorg-community   ?

**Comment by semioticrobotic** [comment]
This is great! Thank you. I made some edits and additions but needed to log off for the night. Left a small outline of my thinking for your feedback. Happy to include more community history in the opening (agree that linking to your series from last year would be perfect).

**Comment by semioticrobotic** [comment]
First draft now under review with @LauraHilliger, @HeidiHVL, and @jenkelchner.

**Comment by semioticrobotic** [comment]
Now in production.

**Comment by semioticrobotic** [comment]
Scheduled for publication on June 02. Happy anniversary, one and all!

**Comment by semioticrobotic** [comment]
And [published](https://opensource.com/open-organization/21/6/celebrate-sixth-anniversary)! Many thanks, @LauraHilliger, for kicking off our anniversary celebration.

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn
