### ISSUE TITLE
Promoting open organizations in non-profit contexts

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#98]
Ambassador @heatherleson recently concluded the work of setting global strategy for a humanitarian non-profit organization—and the Open Organization Definition is part of it. @heatherleson is interested in conducting a short roundtable discussion with @LauraHilliger about integrating/incorporating open principles in various kinds of non-profits. I agreed to start the conversation.

Our initial vision is that this is a structured conversation between @heatherleson, @LauraHilliger, and anyone else who might have experience in this area and like to contribute. @jenkelchner, @semioticrobotic, or someone else entirely can moderate.

**Comment by Hleson** [comment]
Laura and I have been on journeys to build open in our organizations. The approaches are different, however, it would be interesting to share our key lessons on shifting to open in organizations. 

Some background from me:

- [IFRC digital  transformation strategy] (http://digital.ifrc.org/ )is approved by the governing board. (May 2021). It took a few years of groundwork then a big lift last year to deliver. It cites open source, open data, open principles. We championed the open definition as something that could line up with Strategy 2030 and humanitarian principles. 
-The [IFRC Strategy 2030](https://solferinoacademy.com/) includes parallel language and goals to the open definition. This was approved by 192 National Societies around the world. 
-Many projects in IFRC use open source and open data. Now it is no longer a large debate. [Solferino Academy](https://solferinoacademy.com/) creates open innovations with our partners. We default open. 

Looking forward

**Comment by jenkelchner** [comment]
I'm happy to moderate if time permits and we get days to align!

**Comment by LauraHilliger** [comment]
obviously I'm in! Sometime in July?

**Comment by Hleson** [comment]
Great!  I am available between july 5 - 11th. On leave July 12 - 18.   Happy to collaborate

**Comment by semioticrobotic** [comment]
This is going to be great. Looks like @jenkelchner has offered to moderate if everyone's schedules align. I can serve as backup if that's not the case.

**Comment by jenkelchner** [comment]
Happy to moderate @Hleson - I can make time during the week of the 5th dependent on time of day. I'm EST.

**Comment by Hleson** [comment]
Ok, I am also available that week. The friendly cest/est window is 1500 - 1800 CEST. @semioticrobotic @LauraHilliger  - how about you?

**Comment by semioticrobotic** [comment]
I will let @Hleson, @jenkelchner, and @LauraHilliger settle on a time, since they are the essential players in this episode, and will join if possible during the window they set, because I am a Curious Spectator.

**Comment by jenkelchner** [comment]
Happy to moderate while Bryan is away @LauraHilliger @Hleson  - if you can forward me anything in advance that would help me out in supporting this please do :) See ya next week.

**Comment by Hleson** [comment]
Great. I am keynoting on this tomorrow at https://compass.acm.org/ . Then I will share the slides here with all my points.

**Comment by LauraHilliger** [comment]
FYI That was a fantastical chat with @Hleson and thank you for hosting us @jenkelchner. To make it easy for Jen, here's a title and descriptor – feel free to edit at will. Heather - do you want to link to your presentation? We could also link to [the Greenpeace series on OS.com](https://opensource.com/tags/open-organization-greenpeace)

**Getting Started: Openness in non-profits**
[Heather Leson](https://twitter.com/HeatherLeson/) and [Laura Hilliger](https://twitter.com/epilepticrabbit) discuss the deep work they've been doing bringing openness into non-profits like Red Cross/ Red Cresent, Greenpeace and more. They talk about lesson learned, challenges (and overcoming them) and give some tips on how to get started. 

@jenkelchner please let me know if there's anything I can help with!!

**Comment by jenkelchner** [comment]
@LauraHilliger @Hleson - all edits are complete and the video will be scheduled to go live next week -- 14 July 2021. Housed in the new playlist created: Open in Non-Profits

**Comment by semioticrobotic** [comment]
Amazing interview! Thanks for doing this, @Hleson and @LauraHilliger. Gives me a few ideas for future articles and book chapters you might be able to help us create, too. Well done.

**Comment by Hleson** [comment]
thanks @jenkelchner  for all the help. And, @LauraHilliger  for being an ally in this space. Great to talk on tactics and lessons. And, @semioticrobotic you are the most patient person every. It has taken me awhile to move from what I was doing internally to talking openly. Glad to have done that internal socialization so that I can share how this project and people really helped us move the agenda forward. Thank you!

**Comment by jenkelchner** [comment]
Time to get this out there in the public! :)

- [ ] Twitter
- [ ] LinkedIn
- [ ] Discourse

**Comment by semioticrobotic** [comment]
Great work, team! Love this.

**Comment by semioticrobotic** [comment]
I'm leaving this open because I would like to promote again on Twitter, once more, next week. I'll take responsibility for closing after that.
