### ISSUE TITLE
Lessons in openness from Japan's "business reinvention"

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization/editorial#99]
New book review from @RonMcFarland, due in June. Proposed single article without a video component.

@semioticrobotic will work with @RonMcFarland on this.

**Comment by semioticrobotic** [comment]
@RonMcFarland has finished a draft and I am reviewing.

**Comment by semioticrobotic** [comment]
Part 1, with suggested revisions, now back to @RonMcFarland for review.

**Comment by semioticrobotic** [comment]
@RonMcFarland and @semioticrobotic have finished revisions. Tapped @trncb to see if he might have time to copy edit for us.

**Comment by trncb** [comment]
Thanks @semioticrobotic . Will have a look in the next couple of days.

**Comment by semioticrobotic** [comment]
Always appreciate you, @trncb. Thanks.

**Comment by semioticrobotic** [comment]
Scheduled for publication on July 8, 2021.

**Comment by semioticrobotic** [comment]
[Published](https://opensource.com/open-organization/21/7/japan-business-reinvention)! Congrats, Ron.

**Comment by semioticrobotic** [comment]
### Promotion checklist

- [ ] Discourse
- [ ] Twitter
- [ ] LinkedIn

**Comment by RonMcFarland** [comment]
Bryan,

Great!  I'll start forwarding it around.

Ron
